### ISSUE TITLE
Interpolation (dense) output changes the order of the time points supplied

### ISSUE THREAD

**Issue by dawbarton** [JuliaDiffEq/OrdinaryDiffEq.jl#10]
At the moment the dense interpolation routines change the order of the time points supplied (by sorting the input vector in place, hence silently changing the input unexpectedly). This is unexpected and surprising and can easily lead to errors. Moreover, with the new Julia vectorisation syntax you might expect that `sol([1.0, 0.5])` is the same as `sol.([1.0, 0.5])` but it is not.

Whilst this might not be a common usage, I have used it repeatedly when randomly sampling from a simulated trajectory.

**Comment by dawbarton** [comment]
See #11 for a fix.

**Comment by ChrisRackauckas** [comment]
That sounds reasonable enough and the fix is simple enough that it should be changed.

**Comment by ChrisRackauckas** [comment]
BTW you caught this right in time for a tagging spree. It should be tagged later today then.

**Comment by ChrisRackauckas** [comment]
Fixed by #11.
