### ISSUE TITLE
Exprb43 and Exprb32 for SplitODEProblem?

### ISSUE THREAD

**Issue by aarmey** [JuliaDiffEq/OrdinaryDiffEq.jl#1005]
I have a semilinear ODE constructed as a SplitODEProblem. Solving works with `LawsonEuler`, `NorsettEuler`, and `HochOst4`. However, with `Exprb32` or `Exprb43`, I get the following error:

```
Algorithm OrdinaryDiffEq.Exprb43{DataType}(30, 0, true, 0, Val{:forward}) cannnot be used for split problems. Consider reformat to a regular `ODEProblem`
```

In `perform_step!`, I see code checking for a split problem. It looks like maybe the methods are just missing a specialized cache setup function in `linear_nonlinear_caches.jl`?

This is unrelated, but `GenericIIF1` and `GenericIIF2` are mentioned in the documentation but don't seem to be implemented anywhere I can find.

**Comment by YingboMa** [comment]
`Exprb43` and `Exprb32` uses continuous linearization, so it is not designed to solve a `SplitODEProblem`.

**Comment by aarmey** [comment]
Should it be removed from the documentation here then?

https://github.com/JuliaDiffEq/DiffEqDocs.jl/blame/master/docs/src/solvers/split_ode_solve.md#L73

**Comment by YingboMa** [comment]
Yes, definitely, thank you for filing the issue!

**Comment by YingboMa** [comment]
> This is unrelated, but GenericIIF1 and GenericIIF2 are mentioned in the documentation but don't seem to be implemented anywhere I can find.

Since the previous implementation of `GenericIIF1` and `GenericIIF2` were not optimized for the banded structure of the Jacobian matrix, nor they used an optimized modified Newton solver, they have been removed from the library. However, developing optimized implementations is planned.
