### ISSUE TITLE
`chunk_size` not honoured

### ISSUE THREAD

**Issue by mauro3** [JuliaDiffEq/OrdinaryDiffEq.jl#1053]
My understanding is that `chunk_size` will fix the `chunksize` used with `ForwardDiff`.  If this is so, then it's not working:
```julia
using OrdinaryDiffEq, ForwardDiff
const chunksize = 2

function rober(du,u,p,t)
  if eltype(u) <: ForwardDiff.Dual
    if ForwardDiff.npartials(u[1])!=chunksize
      @show chunksize
      @show ForwardDiff.npartials(u[1])
      error()
    end
  end

  y₁,y₂,y₃ = u
  k₁,k₂,k₃ = p
  du[1] = -k₁*y₁+k₃*y₂*y₃
  du[2] =  k₁*y₁-k₂*y₂^2-k₃*y₂*y₃
  du[3] =  k₂*y₂^2
  nothing
end
prob = ODEProblem(rober,[1.0,0.0,0.0],(0.0,1e5),(0.04,3e7,1e4))
sol = solve(prob, TRBDF2(chunk_size=chunksize))
```
prints and errors:
```
chunksize = 2
ForwardDiff.npartials(u[1]) = 3
ERROR: LoadError: 
```

I came across this because I wanted to use `DiffEqBase.dualcache` with a given `chunksize` but it doesn't work.

*Edit*: update due to Chris' comment `chunksize` 55->2

**Comment by ChrisRackauckas** [comment]
The chunksize cannot be larger than the number of terms being differentiated, so ForwardDiff lowered it to its maximum size here.

**Comment by mauro3** [comment]
Bad example... but it also errors with `chunksize = 2`.

**Comment by ChrisRackauckas** [comment]
oh, this must've been dropped in the transition over to sparse differentiation.

**Comment by mauro3** [comment]
I'll discuss this tomorrow with @huanglangwen.
