### ISSUE TITLE
Not fully broadcasting methods

### ISSUE THREAD

**Issue by devmotion** [JuliaDiffEq/OrdinaryDiffEq.jl#106]
Despite https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/pull/104 not all methods are fully broadcasting yet. Mostly this is due to https://github.com/JuliaLang/julia/issues/22255.

Methods that are not fully broadcasting (usually both not in-place and in-place versions if existent):
- [ ] Feagin10
- [ ] Feagin12
- [ ] Feagin14
- [ ] RK4
- [ ] TanYam7
- [ ] DP8
- [ ] TsitPap8
- [ ] OwrenZen4
- [ ] OwrenZen5
- [ ] BS5
- [ ] Tsit5
- [ ] DP5
- [x] GenericImplicitEuler
- [ ] GenericTrapezoid (only in-place)
- [x] ImplicitEuler
- [ ] Trapezoid
- [x] TRBDF2
- [ ] Hairer4/Hairer42 (only in-place)
- [ ] KenCarp4 (only in-place)
- [ ] Kvaerno5 (only in-place)
- [ ] KenCarp5 (only in-place)
- [ ] IRKN3
- [ ] IRKN4
- [ ] DPRKN6
- [ ] DPRKN8
- [ ] DPRKN12
- [ ] ERKN4
- [ ] Nystrom5VelocityIndependent
- [ ] Rosenbrock23 (only in-place)
- [ ] Rosenbrock32 (only in-place)
- [ ] Rosenbrock33 (only in-place)
- [ ] Rosenbrock34 (only in-place)
- [ ] Rosenbrock4 (only in-place)
- [ ] Rodas4 (only in-place)
- [ ] Rosenbrock5
- [ ] Vern6
- [ ] Vern7
- [ ] Vern8
- [ ] Vern9

DP5Threaded is by design not broadcasting.

Moreover, we have to assure that also corresponding interpolation methods are broadcasting.

**Comment by devmotion** [comment]
We also have to get rid of lines such as https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/src/integrators/rosenbrock_integrators.jl#L55-L57 in order to get fully broadcasting methods. Just replacing them with `@. W = mass_matrix - γ*J` does not work (see https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/pull/104#issuecomment-320346665). Maybe we can use something like
```julia
if typeof(mass_matrix) <: UniformScaling
    W .= mass_matrix - dt*J
else
    @. W = mass_matrix - dt*J
end
```
?

**Comment by ChrisRackauckas** [comment]
I think there are some Runge-Kutta Nystrom methods in this list as well.

**Comment by ChrisRackauckas** [comment]
Maybe https://github.com/JuliaLang/julia/pull/23912 fixes https://github.com/JuliaLang/julia/issues/22255?

**Comment by ChrisRackauckas** [comment]
https://github.com/JuliaLang/julia/issues/22255 is fixed on Julia master!

**Comment by YingboMa** [comment]
Sadly, we still need to wait for the fix for https://github.com/JuliaLang/julia/issues/28126.

**Comment by YingboMa** [comment]
With https://github.com/JuliaLang/julia/pull/30973, I got
```julia
julia> @btime solve($(ODEProblem((du,u,p,t)->@.(du=0.01*u), ones(100), (0,100.))), Tsit5(), save_on=false); # loop
  13.446 μs (100 allocations: 28.83 KiB)

julia> @btime solve($(ODEProblem((du,u,p,t)->@.(du=0.01*u), ones(100), (0,100.))), Tsit5(), save_on=false); # broadcast
  13.075 μs (100 allocations: 28.83 KiB)
```
:tada:

**Comment by ChrisRackauckas** [comment]
@YingboMa got all of DiffEq with https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/pull/716 which actually sped things up.

**Comment by YingboMa** [comment]
No, not all of them. `Feagin`s doesn't have broadcasting.

**Comment by ChrisRackauckas** [comment]
https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/issues/718 any others?
