### ISSUE TITLE
LeapfrogMagnus

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/OrdinaryDiffEq.jl#1062]
Following https://joshuagoings.com/2017/06/15/magnus/

**Comment by ChrisRackauckas** [comment]
@Biswajitghosh98

**Comment by Biswajitghosh98** [comment]
@ChrisRackauckas  Thanks a lot for tagging me on this issue! I'll implement the MMUT method.

**Comment by Biswajitghosh98** [comment]
@ChrisRackauckas Please take a look at the PR https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/pull/1081
