### ISSUE TITLE
Regression tracking

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/OrdinaryDiffEq.jl#107]
Put on the wrong repo. Continuing: https://github.com/JuliaDiffEq/DiffEqBase.jl/issues/61

No change with muladd macro (at 1.16.0)

**Comment by ChrisRackauckas** [comment]
Current master

![master](https://user-images.githubusercontent.com/1814174/28992911-01136c50-795e-11e7-8fed-711f2179ae49.PNG)

**Comment by ChrisRackauckas** [comment]
![broadcast_pr](https://user-images.githubusercontent.com/1814174/28992932-910b1c7c-795e-11e7-8f7a-600f2a451bb6.PNG)

@devmotion this is the broadcast_pr. Can we find out what exactly it is? It's pretty universal so it must be in something like initdt

**Comment by ChrisRackauckas** [comment]
Before:

![broadcast_pr_stiff_2](https://user-images.githubusercontent.com/1814174/28992964-b743307c-795f-11e7-886b-3d03c9fb51d0.PNG)

After:

![after_pr](https://user-images.githubusercontent.com/1814174/28992965-c293326a-795f-11e7-9261-23c5f9fe568d.PNG)

Before:

![before_pr_stiff](https://user-images.githubusercontent.com/1814174/28992967-d56a2470-795f-11e7-9892-8199774bf324.PNG)


After:

![broadcast_pr_stiff](https://user-images.githubusercontent.com/1814174/28992972-df75c58c-795f-11e7-8e67-37257f3770d1.PNG)

**Comment by ChrisRackauckas** [comment]
So element-wise tolerances had a non-trivial performance hit. But that's understandable. Can we inline the interators even without Iterators.jl? If not, hopefully this is just a place where broadcast won't cause a performance hit and that would be the problem anyways. Something to check at least.

**Comment by ChrisRackauckas** [comment]
But https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/pull/104 definitely has performance hits. Linear RK shows they are pretty widespread so there must be something in a core routine (init_dt?) However, Rodas5 had a big performance hit. We might want to break apart that PR and carefully benchmark it.

**Comment by devmotion** [comment]
So these plots are all current master vs. https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/pull/104?

I'm just reproducing these plots in the linear RK and ROBER benchmarks, both for master and https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/pull/104 (I already get slower slower results for master than you, so I should have done that comparisons already when I posted my first plots yesterday...).

I also studied the linear RK benchmarks, and since the ODE problem is in-place the benchmarked OrdinaryDiffEq methods such as Tsit5 or DP5 are implemented in exactly the same way both on master and in this PR (I only changed not in-place methods for these algorithms). So the only explanation I see would be a difference in initdt - however the broadcast limit is never hit in initdt, so I'm a bit surprised about these findings.

For the Rosenbrock methods there could be another/additional factors coming into play: in addition to broadcasting small operations (longer operations are still implemented as for loops in Rodas5 or Rodas4 e.g.) I also changed the calculation of `W` for not in-place methods (we discussed that yesterday) and added brackets to the in-place versions of Rodas4 and Rodas5 which were already present in the not in-place versions (I mentioned that some days ago, I guess). These brackets assure that parts of the sum-multiplication complexes are summed before they're added to `uprev` - removing the brackets in the not in-place methods, as you suggested, increased the errors of the solutions so dramatically that multiple of the Rosenbrock tests failed. Hence to assure same results for both not in-place and in-place methods I just added these brackets to the in-place version as well.

So, after the benchmarks for master and this PR are redone, I will do the following two things:
1. I replace the complete initdt methods of the PR with those of master and see if this improves the benchmarks.
2. I remove the changes of the Rosenbrock methods that are unrelated to broadcasting and see if this improves the ROBER benchmarks.

**Comment by devmotion** [comment]
I got some results regarding point 1:

First of all, I could reproduce your results. In the following, I redid all plots of https://github.com/JuliaDiffEq/DiffEqBenchmarks.jl/blob/master/NonStiffODE/Linear%20Work-Precision%20Diagrams.ipynb. As initial plot of these benchmarks I get on master
![figure_1_linear_master](https://user-images.githubusercontent.com/26102/28997685-eb9b61da-7a1a-11e7-833b-3256fe30dae3.png)
and with the PR
![figure_1_linear_pr](https://user-images.githubusercontent.com/26102/28997691-0b0b4832-7a1b-11e7-8332-0f364f2be910.png)
So there clearly is a regression. Replacing initdt.jl with the version of the master branch I obtain
![figure_1_linear_pr_oldinitdt](https://user-images.githubusercontent.com/26102/28997701-2478abca-7a1b-11e7-8342-29308edc4bf0.png)
However, more interestingly by further optimization and some additional cleanup (just pushed my changes to the PR) the first benchmark gives
![figure_1_linear_pr_initdt](https://user-images.githubusercontent.com/26102/28997713-50519888-7a1b-11e7-964f-fdc4e85b1ee3.png)
which is on par with the current master branch. So I wanted to know which of the changes (removed creation of some empty arrays, removed duplicate calculations and called `oneunit` only once) was the most significant one. It seems only the `oneunit` change leads to any significant improvement, as the benchmark with only this change implemented shows:
![figure_1_linear_pr_initdt_oneunit](https://user-images.githubusercontent.com/26102/28997745-84a1ca94-7a1c-11e7-9378-6ecfe5710b1f.png)

**Comment by ChrisRackauckas** [comment]
Cool. And can you reproduce the first part of the results about elementwise tolerances? (https://github.com/JuliaDiffEq/DiffEqBase.jl/issues/61)

**Comment by ChrisRackauckas** [comment]
>which is on par with the current master branch. So I wanted to know which of the changes (removed creation of some empty arrays, removed duplicate calculations and called oneunit only once) was the most significant one. It seems only the oneunit change leads to any significant improvement, as the benchmark with only this change implemented shows

Thanks. That's very helpful. That means broadcast doesn't hoist function calls, which is something to watch out for in the future. Let me run generate some plots and see where we're at.

**Comment by ChrisRackauckas** [comment]
I can confirm the `initdt` fix fixes the regression on master. When I do the ROBER tests

https://github.com/JuliaDiffEq/DiffEqBenchmarks.jl/blob/master/StiffODE/ROBER.ipynb

I still see a big regression with Rodas5. Same is seen in the VanDerPol tests. But that method is the only one that I am seeing regressions with. So I think the PR is safe to merge only after Rodas5 gets a fix.

**Comment by devmotion** [comment]
I discovered the problem with Rodas5. Accidentally I hit the broadcast limit - moving the affected line back into a loop leads to the following results (still with added brackets to synchronize in-place and not in-place methods):
On master
![figure_5_master](https://user-images.githubusercontent.com/26102/28998616-494daa94-7a30-11e7-9bf7-e62140c1abaf.png)
And with the PR
![figure_5_pr_initdt](https://user-images.githubusercontent.com/26102/28998622-5dec5360-7a30-11e7-99b1-dc00fbc24d88.png)

**Comment by ChrisRackauckas** [comment]
I think the speedup that you saw may have been because broadcast fixes the performance regression due to elementwise tolerances. Would you mind checking that out more? Make this loop a normal loop:

https://github.com/devmotion/OrdinaryDiffEq.jl/blob/d91da02c05e56e6dc5cea31bae938d35c21794f2/src/integrators/low_order_rk_integrators.jl#L445

and see where that gets you to (using the linear ODE workprecision benchmarks). Then pull this out to broadcast:

https://github.com/devmotion/OrdinaryDiffEq.jl/blob/d91da02c05e56e6dc5cea31bae938d35c21794f2/src/integrators/low_order_rk_integrators.jl#L447

See if that has a regression at all.

**Comment by devmotion** [comment]
OK, I'll investigate that 👍

**Comment by ChrisRackauckas** [comment]
It looks like the Rodas5 fix worked. Once tests pass I'll merge and then we just have elementwise tol to check.

**Comment by ChrisRackauckas** [comment]
Spoke a little too fast. Comparing

PR:

https://travis-ci.org/JuliaDiffEq/OrdinaryDiffEq.jl/jobs/261394443

Master:

https://travis-ci.org/JuliaDiffEq/OrdinaryDiffEq.jl/jobs/261250591

Discretre Tests, Rosenbrock Tests, Adaptive Tests, Partitioned Methods Tests, SSPRK Tests, etc. have regressions in not just test time but also allocations. Can we find out if these are real or if it's compilation time?

**Comment by devmotion** [comment]
So, for the test you proposed I got the following results in the linear ODE benchmarks:

1. Current master:
![figure_1_linear_master](https://user-images.githubusercontent.com/26102/28998826-cef4dcb8-7a34-11e7-84d2-958864ac8cc2.png)

2. master with a normal loop, i.e. with
```julia
    @tight_loop_macros for i in uidx
      @inbounds utilde[i] = uprev[i] + dt*(b1*k1[i] + b2*k2[i] + b3*k3[i] + b4*k4[i] + b5*k5[i] + b6*k6[i] + b7*k7[i])
      @inbounds atmp[i] = (utilde[i]-u[i])/(integrator.opts.abstol+max(abs(uprev[i]),abs(u[i]))*integrator.opts.reltol)
    end
```
![figure_1_linear_master_loop](https://user-images.githubusercontent.com/26102/28998834-f3a4aa16-7a34-11e7-9f6b-c5355148dcc4.png)

3. master with normal loop and broadcasting, i.e. with
```julia
    @tight_loop_macros for i in uidx
      @inbounds utilde[i] = uprev[i] + dt*(b1*k1[i] + b2*k2[i] + b3*k3[i] + b4*k4[i] + b5*k5[i] + b6*k6[i] + b7*k7[i])
    end
    @. atmp = (utilde-u)/(integrator.opts.abstol+max(abs(uprev),abs(u))*integrator.opts.reltol)
```
![figure_1_linear_master_loop_broadcast](https://user-images.githubusercontent.com/26102/28998981-9427ec70-7a38-11e7-9487-b13221fe22ed.png)

**Comment by ChrisRackauckas** [comment]
1 vs 2 is a clear difference. 2 vs 3, when you run it a few times does it keep that difference? I'm mostly looking at error `1e0` and `1e-6`. Can we find out how to make that broadcast not regress? Maybe

```julia
atol,rtol = integrator.opts.abstol,integrator.opts.reltol
@. atmp = (utilde-u)/(atol+max(abs(uprev),abs(u))*rtol)
```

?

**Comment by devmotion** [comment]
These differences are real. I redid both 2 and 3 twice, I was also wondering about these differences, and got the same difference in these two points in every run.

```julia
atol,rtol = integrator.opts.abstol,integrator.opts.reltol
@. atmp = (utilde-u)/(atol+max(abs(uprev),abs(u))*rtol)
```
leads to exactly the same regressions.

**Comment by ChrisRackauckas** [comment]
Well we should redefine `utilde` so that way it's `atmp = utilde/(atol+max(abs(uprev),abs(u))*rtol)`. Then is there any way to write a function `err_calc(atmp,utilde,uprev,u,integrator)` that can do this efficiently and do the different cases? But hopefully broadcast? Sounds like that's a no and this might just be the cost of broadcast?

**Comment by devmotion** [comment]
Maybe it's partly possible if we do not dispatch on `integrator` but on `abstol` and `reltol`? Then a call to `err_calc(atmp,utilde::Vector{T},uprev,u,abstol::Number,reltol::Number)` could just do the calculations in a normal for loop and we only get a regression in the other cases that need broadcasting anyway?

**Comment by ChrisRackauckas** [comment]
That might be overengineering. The hit is probably just due to the broadcast mechanism which allocates some views, and that should get fixed in the near future. And it's not much. Let me get a second opinion on this. @dextorious ?

**Comment by devmotion** [comment]
I just tried this idea with the following two simple function definitions
```julia
@inline function calculate_residuals!(atmp::Array{T}, utilde::Array{T}, uprev::Array{T}, 
				      u::Array{T}, abstol::T, reltol::T) where {T<:Number}
  @tight_loop_macros for i in eachindex(atmp)
    @inbounds atmp[i] = utilde[i]/(abstol+max(abs(uprev[i]),abs(u[i]))*reltol)
  end
end

@inline function calculate_residuals!(atmp, utilde, uprev, u, abstol, reltol)
  @. atmp = utilde/(abstol+max(abs(uprev),abs(utilde))*reltol)
end
```
and in Tsit5Cache the lines
```
    @tight_loop_macros for i in uidx
      @inbounds utilde[i] = uprev[i] - u[i] + dt*(b1*k1[i] + b2*k2[i] + b3*k3[i] + b4*k4[i] + b5*k5[i] + b6*k6[i] + b7*k7[i])
    end
    calculate_residuals!(atmp, utilde, uprev, u, integrator.opts.abstol, integrator.opts.reltol)
```
Then as expected there is no regression:
![figure_1_linear_master_dispatch](https://user-images.githubusercontent.com/26102/28999493-e1616d94-7a48-11e7-9d47-a19d848f367f.png)

Do you think we should use something like this? Of course, we should define some `btilde` then to calculate `utilde`.

**Comment by ChrisRackauckas** [comment]
Yeah, that sounds like a great solution that can actually decrease the amount of code.

**Comment by dextorious** [comment]
I like this solution as well. On the more general point, insofar as we expect the view allocation issue to be resolved in the foreseeable future, further specialization would be overkill. That's really the key point, though, and I'm not sure as to the expected timeline for that fix to become part of mainline Julia.

**Comment by ChrisRackauckas** [comment]
Yeah this sounds good. It has one extra function as a workaround for now, and we can delete that one function in the future. Setting everything up with `calculate_residuals!` will reduce the total amount of code too. Let's get this in and we can call this case closed.

**Comment by ChrisRackauckas** [comment]
Fixed. Thanks @devmotion
