### ISSUE TITLE
Two-step RKN Methods

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/OrdinaryDiffEq.jl#110]
http://waset.org/publications/1175/numerical-solution-of-second-order-ordinary-differential-equations-by-improved-runge-kutta-nystrom-method

**Comment by ChrisRackauckas** [comment]
@YingboMa would you want to do IRKN3 to finish this up?

**Comment by YingboMa** [comment]
Sure

**Comment by YingboMa** [comment]
Closed by #150
