### ISSUE TITLE
More RKN Methods

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/OrdinaryDiffEq.jl#111]
It looks like what's left here is the following:

- [x] `DPRKN6` dense output
- [x] `ERKN4(3)M`
- [x] `DPRKN12`

The Tsitorious method is actually a symplectic method and it seems oddly unoptimized compared to the current 10th order method since it's built from an RKN instead... 

## Old Op

http://www.m-hikari.com/ams/ams-2017/ams-17-20-2017/p/dembaAMS17-20-2017.pdf

Classic Dormand-Prince method:
http://ac.els-cdn.com/0898122187900666/1-s2.0-0898122187900666-main.pdf?_tid=61743dba-7a92-11e7-8ab1-00000aab0f01&acdnat=1502015657_7434ad24db3c7bafd395f8fbe5f2cead

https://oup.silverchair-cdn.com/oup/backfile/Content_public/Journal/imajna/7/2/10.1093/imanum/7.2.235/2/7-2-235.pdf?Expires=1502109211&Signature=Kb~ULYQWmSj~Ci8zoNLOjYECciteCDWhsykLVvTtbGws1fDW3vX5fY1QVgv~NdJD4dDAq-KY8a84tC-bIpNF7XQ8ZG29ze4cKO9YVgfS972RsVdcJEcHsyLmGH6zA-hF56k8-2qX8L7x4p8exQ2xd4H39mNw3KFOwjGaMSXDwR40LKlRldS1q0T~I2LRufmx-V5ZwWXZqZOtxJjy5nPlv~GNCrvhO7GTpGrtJuI5s8Lqocf-5~Je9ooQT5IRnWtfJ4i6Dq3raMOyR~v1m~qkjlWPuzIRJj6li8NBAHEdugadllPXw~eeNATbZJggRvCdfrFoATZ5uZIywg4yLnt2eQ__&Key-Pair-Id=APKAIUCZBIA4LVPAVW3Q

Super accurate and high order:
https://academic.oup.com/imajna/article/7/4/423/841290

Symmetric and Symplectic
https://link.springer.com/content/pdf/10.1023%2FA%3A1008346516048.pdf

**Comment by ChrisRackauckas** [comment]
It looks like what's left here is the following:

- [ ] `DPRKN6` dense output
- [ ] `ERKN4(3)M`
- [ ] `DPRKN12`

**Comment by YingboMa** [comment]
Closed by #168 #162 #158
