### ISSUE TITLE
Strang splitting

### ISSUE THREAD

**Issue by jagot** [JuliaDiffEq/OrdinaryDiffEq.jl#116]
For composed linear operators of the type `F = A + B + C + ...`, there should, in addition to the normal methods (implicit Euler, Crank–Nicolson, etc), which operate using `F*u` and `F\u`, an operator splitting method which approximate the propagator as `...exp(C/2)exp(B/2)exp(A)exp(B/2)exp(C/2)...` with automatic symmetric placement of the exponentials. My suggestion is that the first operator should be placed inner-most.

**Comment by ChrisRackauckas** [comment]
I'll make the most basic version today which just does two operators to see what's required, and that skeleton would be easy to build off of.

**Comment by ChrisRackauckas** [comment]
The basic version is up and just is fixed at `exp(B/2)exp(A)exp(B/2)`. It shows there's an error in the way the `expm` was setup though, so right now it just grabs the internal arrays. Something better needs to be done there.

https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/commit/9ee72aecedb9d27ee73b72183f754dfc378298ac

**Comment by ChrisRackauckas** [comment]
Is this all under the topic of Lie group integrators? If so, there's a gold mine of methods. Hairer III labels them as Magnus, Crouch-Grossman methods, and Munthe-Kaas

https://arxiv.org/pdf/1207.0069.pdf
http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.30.7762&rep=rep1&type=pdf

And an adaptive timestepping one:

https://link.springer.com/content/pdf/10.1007%2Fs10483-008-0901-5.pdf

**Comment by ChrisRackauckas** [comment]
Superseded by https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/issues/1063
