### ISSUE TITLE
Broken link in readme

### ISSUE THREAD

**Issue by mschauer** [JuliaDiffEq/OrdinaryDiffEq.jl#136]
http://docs.juliadiffeq.org/latest/solvers/refined_ode_solve.html

**Comment by ChrisRackauckas** [comment]
Oh yes, that page was split up. The part of interest would be here now: 

http://docs.juliadiffeq.org/latest/solvers/dynamical_solve.html

**Comment by ChrisRackauckas** [comment]
Fixed
