### ISSUE TITLE
rootfind_event_loc does not work if the event is not called event_f

### ISSUE THREAD

**Issue by ronisbr** [JuliaDiffEq/OrdinaryDiffEq.jl#15]
Hi!

If I set `rootfind_event_loc = true`, then it will fail if the event is not called `event_f`. This is caused due to a missing `$` here:

https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/src/callbacks.jl#L42

**Comment by ChrisRackauckas** [comment]
Fixed via https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/commit/54303f58406b8ba1277b61af63924eae9070bbbd . Thanks!
