### ISSUE TITLE
Set event_occured  to false at the end of @ode_event

### ISSUE THREAD

**Issue by ronisbr** [JuliaDiffEq/OrdinaryDiffEq.jl#16]
Hi @ChrisRackauckas,

It turns out that I could not add more than one event to the callback function. After looking at the code, I realized that the problem is that `event_occured` is set to `false` at `@ode_callback` macro and the macro `@ode_event` does not set it to `false` at the end. Hence, if we have:

```
callback = @ode_callback begin
    @ode_event event_f1 ...
    @ode_event event_f2 ...
end
```

Then the `event_f2` will always be executed when `event_f1` happened. A workaround it to manually set `event_occured` to `false` between those two calls:

```
callback = @ode_callback begin
    @ode_event event_f1 ...
    event_occured = false
    @ode_event event_f2 ...
end
```

See an example here:

https://gist.github.com/ronisbr/a89021585266af326df7c77d1f0e9943

By the way, i think `event_occured` is misspelled.

**Comment by ChrisRackauckas** [comment]
>By the way, i think event_occured is misspelled.

👍 . I find/replaced it all throughout the OrdinaryDiffEq.jl and the docs. Thanks for pointing that out!

>Then the event_f2 will always be executed when event_f1 happened. A workaround it to manually set event_occured to false between those two calls:

I think the easy fix is to just set `event_occurred=false` at the bottom of the event macro. It's essentially no cost to have it there, and makes this much nicer. 

But I think that there's an overarching thing to think about: should events be chained like this, or should you just make a `event_f` which hits 0 in multiple different ways, and find out how in `apply_event!`? What's the pros and cons here?

There is one con to chaining events like you did, and that there's an extra save in there if both events happen in the same timepoint. What it will do is:

- Save
- Apply event
- Save

for each event, so for two events that's

- Save
- Apply event
- Save 
- Save
- Apply event
- Save

So maybe we need to change something so it knows to not save two times in the middle there. That's probably just a boolean.

**Comment by ronisbr** [comment]
I see the point. What do you think about @ode_event accept an array of events? Then it can iterate and search for which events happened and then execute the event functions. This way, @ode_event can save things just once.

**Comment by ChrisRackauckas** [comment]
That could work. I wonder, does the ordering of the array and the events matter?

**Comment by ronisbr** [comment]
That's is definitely a possibility. Maybe we can let this to the user. For example, if there is an array telling which events occurred, then the user can decide if the function of another event will be executed or not. I know that this can lead the different results depending of how the user stacked the events in the array. But I think this can be documented so that the user is aware of the behavior.

So, I suggest the following:

1. Test all events in the stack and put the results in an array, which is available to the `apply_event!`.
2. Execute each `apply_event!` in the order decided by the user.
3. Save everything.

Hence, if one event affects the other, then the user must handle in `apply_event!` given the order he/she chooses in the event array.

What do you think?

**Comment by ChrisRackauckas** [comment]
That could make sense.

Now how do you make this all make sense with rootfinding? The more classic case is where the event is not known in advance, so you have to rootfind to find the time of the event. I assume that this "multiple-events take place at the same time" issue doesn't show up in this case, but I am just trying to think of a good implementation for rootfinding each event. It might even be easier to have an array of events expand to be the same as

```
callback = @ode_callback begin
    @ode_event event_f1 ...
    event_occured = false
    first_save = false
    @ode_event event_f2 ...
end
```

**Comment by ronisbr** [comment]
@ChrisRackauckas I forgot about that. You are right, the way you proposed seems very reasonable. So, all we need is a macro to expand the array into that code right?

**Comment by ChrisRackauckas** [comment]
Yeah, that would work.

**Comment by ChrisRackauckas** [comment]
The new callbacks address this.
