### ISSUE TITLE
Calling terminate! in a callback produces an incorrect answer in sol with out-of-place problems

### ISSUE THREAD

**Issue by ikirill** [JuliaDiffEq/OrdinaryDiffEq.jl#199]
```
function test1()
    f(t, u) = [u[1]]
    cb = ContinuousCallback((t,x,_int) -> (@show t, x[1]; x[1] - exp(1)), int -> (println("Stop!"); DE.terminate!(int)))
    prob = ODEProblem(f, [1.0], (0.0, 2.0), callback=cb)
    sol = DE.solve(prob, DE.DP8())
    @printf "Error: %.2e\n" abs(sol[1,end]/exp(1) - 1)
    sol
end
```

Output:

```
...
omitted
...

(t, x[1]) = (0.9999934025713091, 2.718281828459046)
(t, x[1]) = (0.9999934025713086, 2.718281828459045)
Stop!
Error: 5.57e-01
Timeseries Solution with uType Array{Float64,1} and tType Float64
retcode: Success
Interpolation: specialized 7th order interpolation
t:
4-element Array{Float64,1}:
 0.0     
 0.237167
 0.999993
 0.999993
u:
4-element Array{Array{Float64,1},1}:
 [1.0]    
 [1.26765]
 [4.23201]
 [4.23201]
```

So it stops integration correctly, but probably the number that goes into sol is after the full timestep, not taking into account terminate!, or something like that.

**Comment by ChrisRackauckas** [comment]
Can you check if this is specific to out-of-place functions? I.e., try using

```julia
f(t, u,du) = du.=u
```

**Comment by ikirill** [comment]
Yes, it's specific, that change fixes it.

**Comment by ChrisRackauckas** [comment]
I think the larger metaissue here is that we have really good test coverage for event handling with inplace functions (in fact, in general inplace test coverage is better since I'd assume >95% of actual users will be solving systems of DEs). All of your issues seem to occur with out of place functions + events, which is not well covered. We should not only fix up these issues, but extend the event and cache tests to this case.

**Comment by ChrisRackauckas** [comment]
The relevant callback code is here:

https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/src/callbacks.jl#L136

with the way that time is supposed to be "pulled back" being this function:

https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/src/callbacks.jl#L138
https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/src/integrators/integrator_interface.jl#L1

For some reason that may not be actually pulling it back when the function is out-of-place and the type is mutable. This might be do to some kind of pointers issues and it might need an `if typeof(integrator.cache) <: OrdinaryDiffEqConstantCache` (that would catch all of the out-of-place versions).
