### ISSUE TITLE
Add Stabilized Explicit Methods (ROCK2, ROCK4, RKC)

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/OrdinaryDiffEq.jl#2]
Original papers:
http://www.dumkaland.org/publications/content.pdf
https://pdfs.semanticscholar.org/20d2/7edfabdcc9d2b6bfdc3106d192f2f4624d14.pdf
https://infoscience.epfl.ch/record/182114/files/gamm_2002_rock4.pdf

There's a good discussion in Hairer II

also: http://www.dumkaland.org/publications/bit98medovikov.pdf
http://www.dumkaland.org/publications/ComputerScience.pdf

**Comment by ChrisRackauckas** [comment]
http://www.unige.ch/~vilmart/paper_pirock.pdf
https://onlinelibrary.wiley.com/doi/pdf/10.1002/num.21704
https://www.sciencedirect.com/science/article/pii/S0377042715006056
https://www.sciencedirect.com/science/article/pii/S0021999116303990

**Comment by deeepeshthakur** [comment]
This issue can be closed as all these methods are done IIRC.

**Comment by ChrisRackauckas** [comment]
SERK and PIROCK?

**Comment by deeepeshthakur** [comment]
Yeah they are incomplete.
