### ISSUE TITLE
Using ForwardDiff on function containing solve

### ISSUE THREAD

**Issue by lijas** [JuliaDiffEq/OrdinaryDiffEq.jl#202]
I am trying to use ForwardDiff.jl to take the gradient of a function that uses `DifferentialEquations.solve`. The function then uses the solution from `solve` to come up with a function value.  Unfortunately I cant get it to work, see the MWE and error message below. Anyone knows if this is possible to do? I know this is a weird thing I am trying to achieve, so I am not hoping for a solution to much :P 

```
using DifferentialEquations
using ForwardDiff

function run_me()
    f(x) = optimze_me(x)
    @show f(rand(10))
    @show ForwardDiff.gradient(f, rand(10)) 
end

function optimze_me(opt_paras::Vector{T}) where T
    u0 = [one(T), zero(T), zero(T)]
    prob = ODEProblem((t, u) -> lorenz(t,u,opt_paras),u0,(0.0,100.0))
    sol = solve(prob, Tsit5(), dt=0.001)
    #Use solution (sol) to calculate som function value
    #(in this case I just do something simple) 
    f = sol.u[1][1];
    return f
end

function lorenz(t::Float64, u::Vector{T}, opt_paras::Vector{T2}) where {T,T2}
    du = zeros(T2, 3)
    du[1] = opt_paras[1] * 10.0*(u[2]-u[1])
    du[2] = opt_paras[2] * u[1]*(28.0-u[3]) - u[2]
    du[3] = opt_paras[3] * u[1]*u[2] - (8/3)*u[3]
    return du
end 
```
Here is part of the error and stacktrace.

```
julia> run_me()
f(rand(3)) = 1.0
ERROR: MethodError: Cannot `convert` an object of type ForwardDiff.Dual{ForwardDiff.Tag{#f#1,0xb046287d533b082d},Float64,3} to an object of type Float64
This may have arisen from a call to the constructor Float64(...),
since type constructors fall back to convert methods.
Stacktrace:
 [1] perform_step!
```

**Comment by ChrisRackauckas** [comment]
To do this, because of adaptive timestepping, you need to make time also a dual number, i.e. `(T(0.0),T(100.0))`. This dependency cannot be changed because if you think about it, if the initial condition changes then the timesteps change too so they have a derivative component to propagate. 

Other changes I see are that you can use the inplace form:

```julia
function lorenz(t, u, opt_paras,du) where {T,T2}
    du[1] = opt_paras[1] * 10.0*(u[2]-u[1])
    du[2] = opt_paras[2] * u[1]*(28.0-u[3]) - u[2]
    du[3] = opt_paras[3] * u[1]*u[2] - (8/3)*u[3]
end 
```

Let me know if you need anything else.

**Comment by lijas** [comment]
Wow, it actually worked. Thanks alot. (I also had to change `t::T` in the `lorenz`-function) 

One thing I noticed: If I add `solve(..., saveat = 0.1, ...)` I get a error saying 
```
ERROR: rem not defined for ForwardDiff.Dual{ForwardDiff.Tag{#f#73,0xb046287d533b082d},Float64,10}
Stacktrace:
 [1] steprem(::ForwardDiff.Dual{ForwardDiff.Tag{#f#73,0xb046287d533b082d},Float64,10}, ::ForwardDiff.Dual{ForwardDiff.Ta
g{#f#73,0xb046287d533b082d},Float64,10}, ::ForwardDiff.Dual{ForwardDiff.Tag{#f#73,0xb046287d533b082d},Float64,10}) at .\
range.jl:143
```

**Comment by ChrisRackauckas** [comment]
Write the range yourself:

```julia
solve(..., saveat = 0:0.1:100, ...)
```

That seems to work just fine. That looks like a ForwardDiff issue with dual numbers in ranges, with the `steprem` function not defined for Dual numbers. @jrevels is this a known issue or should I document this more? In any case, if you just avoid ranges of dual numbers you're fine.

**Comment by ChrisRackauckas** [comment]
Closing that because now it's reduced to a ForwardDiff.jl issue which is linked.
