### ISSUE TITLE
Normalization at every step

### ISSUE THREAD

**Issue by ronisbr** [JuliaDiffEq/OrdinaryDiffEq.jl#203]
Hi @ChrisRackauckas ,

I have a doubt about the usage of OrdinaryDiffEq.

I am using this package to propagate the attitude using quaternions. The problem is that depending on the step, the integration will provide a non-unitary quaternion. There are a lot of methods to solve this. One of them is to compute the quaternion derivative using an equation that depends on the sampling step. However, I don't know if I have such information inside the dynamic function, do I?

Other method, much easier, is to force the normalization after every sampling step. My question is, how can I force this normalization? Can I directly modify the vector `u` inside the dynamic function?

**Comment by ronisbr** [comment]
Here is something describing the problem:

https://math.stackexchange.com/questions/1896379/how-to-use-the-quaternion-derivative

where we can see that the solution is to create a derivative for the quaternion that depends on the actual sampling interval.

**Comment by ChrisRackauckas** [comment]
You have a manifold constraint on your solution. Your manifold is the zero set for `q` s.t. `g(q) = norm(q)`, so you can use http://docs.juliadiffeq.org/latest/features/callback_library.html#Manifold-Conservation-and-Projection-1 . This method will make every step land on the manifold, and it does not change the order of accuracy.

**Comment by ChrisRackauckas** [comment]
Additionally, SSP methods can have step limiters that can be used to enforced constraints more tightly, but you likely won't need that here.

http://docs.juliadiffeq.org/latest/solvers/ode_solve.html#Explicit-Strong-Stability-Preserving-Runge-Kutta-Methods-for-Hyperbolic-PDEs-(Conservation-Laws)-1

**Comment by ronisbr** [comment]
Very nice! I understood about the quaternions, thanks!

However, just to get documented, if I really want to apply a restriction to the result after the iteration, how can I do? Use callbacks?

This can also happen if I am using a direction cosine matrix (which is transformed into a 9x1 vector), and then I would want to apply something like Gram-Schmidt to ensure that the matrix is ortogonal.

**Comment by ChrisRackauckas** [comment]
This page gives an example: http://docs.juliadiffeq.org/latest/features/callback_library.html#Manifold-Conservation-and-Projection-1 . This builds the `DiscreteCallback` which does the projection to the manifold.

```julia
function g(u,resid)
  resid[1] = u[2]^2 + u[1]^2 - 2
  resid[2] = 0
end
cb = ManifoldProjection(g)
```

does a projection so that `u[2]^2 + u[1]^2 = 2` at every step. You can give it as many restrictions as you have components.

**Comment by ChrisRackauckas** [comment]
>This can also happen if I am using a direction cosine matrix (which is transformed into a 9x1 vector), and then I would want to apply something like Gram-Schmidt to ensure that the matrix is ortogonal.

If you know of a better way to project for your problem, yes just implement a `DiscreteCallback`. By the Triangle inequality a projective transformation on each step preserves the order of the method (see Hairer's Geometric Methods book if you want details).

**Comment by ronisbr** [comment]
Thanks @ChrisRackauckas ! You were as helpful as usual :)

**Comment by ronisbr** [comment]
@ChrisRackauckas 

I reproduced the example in the documentation, but I am getting this error:

```julia
ERROR: LoadError: MethodError: no method matching nlsolve(::NLsolve.DifferentiableMultivariateFunction, ::SimWorkspace{Float64})
```

`SimWorkspace` is defined as:

```julia
type SimWorkspace{T} <: DEDataVector{T}
    x::Array{T,1}   # State-vector.
    θ_g::Vector{T}  # True angle at the time of the last gyro measurement.
    θ_gm::Vector{T} # Gyro measurement.
    V_m::Vector{T}  # Voltage commanded to the reaction wheel.
    xu::Vector{T}   # Kalman filter updated state.
    Pu::Matrix{T}   # Kalman filter updated covariance matrix.
end
```

The code is:

```julia
# Control loop callback.
cl_cb = DiscreteCallback(condition_control_loop, control_loop!)

# Manifold constraint to make sure that the quaternion is always unitary.
function quaternion_constraint(u, resid)
    resid[1]  = u[1]^2 + u[2]^2 + u[3]^2 + u[4]^2 - 1
    resid[2]  = 0
    resid[3]  = 0
    resid[4]  = 0
    resid[5]  = 0
    resid[6]  = 0
    resid[7]  = 0
    resid[8]  = 0
    resid[9]  = 0
    resid[10] = 0
end

mc_cb = ManifoldProjection(quaternion_constraint)

# Solver.
cbs  = CallbackSet(cl_cb, mc_cb)
prob = ODEProblem(dyn_eq!, u0, (0.0, tf))
sol  = solve(prob, Tsit5(), callback = cbs, tstops = tstops, saveat=0.01)
```

**Comment by ChrisRackauckas** [comment]
You need this PR for the rootfinder to work with `AbstractArray`s https://github.com/JuliaNLSolvers/NLsolve.jl/pull/117

**Comment by ronisbr** [comment]
Oh, ok, thanks. I think I will use a callback and just force normalization until this is approved.

**Comment by ronisbr** [comment]
Just for the records:

```julia
# Manifold constraint to make sure that the quaternion is always unitary.
function quaternion_constraint(integrator)
    integrator.u[1:4] /= norm(integrator.u[1:4])
end

mc_cb = DiscreteCallback((t,u,integrator)->true, quaternion_constraint)
```

This solution is working perfectly. However, I know that this is not optimal.

**Comment by ChrisRackauckas** [comment]
Well I would,

```julia
# Manifold constraint to make sure that the quaternion is always unitary.
function quaternion_constraint(integrator)
    integrator.u[1:4] /= norm(@view(integrator.u[1:4]))
end

mc_cb = DiscreteCallback((t,u,integrator)->true, quaternion_constraint)
```

This is totally fine, in fact it's probably more efficient for similar results. The `ManifoldProjection` uses a nonlinear rootfinder to get a solution that is local, which turns out to usually be close to the orthogonal projection. But your method is explicit (a lot less expensive), and once again by the Triangle Inequality your method will still preserve order. Your method falls under:

>If you know of a better way to project for your problem, yes just implement a DiscreteCallback

and I would actually suggest this.
