### ISSUE TITLE
Add a test for reinit_callbacks

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/OrdinaryDiffEq.jl#219]

**Comment by ChrisRackauckas** [comment]
A good test that would be similar is a linear ODE with a zero initial condition that has a callback give it a new initial condition. It should both initialize correctly and reinit correctly, and compare to an analytical solution.

**Comment by rudrasohan** [comment]
@ChrisRackauckas  should I be using `cb = ManifoldProjection(f)` for the callback part ?

**Comment by ChrisRackauckas** [comment]
This can use any callback with a non-trivial init. I don't think that holds for ManifoldProjection?

**Comment by ChrisRackauckas** [comment]
Closed by https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/pull/244
