### ISSUE TITLE
ETDRK4 Coefficient generation

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/OrdinaryDiffEq.jl#242]
Fourth-Order Time-Stepping for Stiff PDEs
Aly-Khan Kassam and Lloyd N. Trefethen

http://epubs.siam.org/doi/abs/10.1137/S1064827502410633

```
function cheb(N)
    N==0 && return (0,1)
    x = cos.(pi*(0:N)/N)
    c = [2; ones(N-1,1); 2].*(-1).^(0:N)
    X = repmat(x,1,N+1)
    dX = X-X'
    D  = (c*(1./c)')./(dX+(eye(N+1)))      # off-diagonal entries
    D  = D - Diagonal(sum(D,2)[:])                 # diagonal entries
    D,x
end

N = 20
D,x = cheb(N)
x = x[2:N]
w = .53*x + .47*sin.(-1.5*pi*x) - x # use w = u-x to make BCs homogeneous
u = [1;w+x;-1]
h=1/4

using Juno

function contour_integral(h,M=32,contour_length=30)
    r = 30*exp.(1im*pi*((1:M)-.5)/M) # points along complex circle
    L = D^2; L = .01*L[2:N,2:N] # 2nd-order differentiation
    A = h*L
    E = expm(A); E2 = expm(A/2);
    I = eye(N-1); Z = zeros(N-1,N-1)
    f1 = Z; f2 = Z; f3 = Z; Q = Z

    for j = 1:M
        z = r[j];
        zIA = inv(z*I-A);
        Q = Q + h*zIA*(exp(z/2)-1);
        f1 = f1 + h*zIA*(-4-z+exp(z)*(4-3*z+z^2))/z^2;
        f2 = f2 + h*zIA*(2+z+exp(z)*(z-2))/z^2;
        f3 = f3 + h*zIA*(-4-3*z-z^2+exp(z)*(4-z))/z^2;
    end
    E,E2,real(f1/M),real(f2/M),real(f3/M),real(Q/M)
end

@time E,E2,f1,f2,f3,Q = contour_integral(h,128)

function big_contour_integral(_h,M=32)
    h = big(_h)
    r = 50*exp.(1im*big.(pi)*((1:M)-.5)/M) # points along complex circle
    L = big.(D^2); L = .01*L[2:N,2:N] # 2nd-order differentiation
    A = h*L
    E = big.(expm(Float64.(A))); E2 = big.(expm(Float64.(A/2)));
    I = big.(eye(N-1)); Z = zeros(BigFloat,N-1,N-1)
    f1 = Z; f2 = Z; f3 = Z; Q = Z

    @progress for j = 1:M
        z = r[j];
        zIA = inv(z*I-A);
        Q = Q + h*zIA*(exp(z/2)-1);
        f1 = f1 + h*zIA*(-4-z+exp(z)*(4-3*z+z^2))/z^2;
        f2 = f2 + h*zIA*(2+z+exp(z)*(z-2))/z^2;
        f3 = f3 + h*zIA*(-4-3*z-z^2+exp(z)*(4-z))/z^2;
    end
    E,E2,real(f1/M),real(f2/M),real(f3/M),real(Q/M)
end

@time E,E2,f1,f2,f3,Q = big_contour_integral(h,128)

function multiprecision(_h)
    h = big(_h)
    L = big.(D^2); L = .01*L[2:N,2:N] # 2nd-order differentiation
    A = h*L
    E = big.(expm(Float64.(A))); E2 = big.(expm(Float64.(A/2)));
    A = big.(A); L = big.(L)
    coeff = h^(-2) * L^(-3)
    A2 = A^2
    Q = Float64.((E2-I)/L)
    a = Float64.(coeff * (-4I - A + E*(4I - 3A  + A2)))
    b = Float64.(coeff * (2I + A + E*(-2I + A)))
    c = Float64.(coeff * (-4I - 3A - A2 + E*(4I-A)))
    Float64.(E),Float64.(E2),a,b,c,Q
end

@time Ẽ,Ẽ2,ã,b̃,c̃,Q̃2 = multiprecision(h)

println("E diff: ", Float64.(norm(E-Ẽ, Inf)))
println("E2 diff: ",Float64.(norm(E2-Ẽ2,Inf)))
println("f1 diff: ",Float64.(norm(f1-ã, Inf)))
println("f2 diff: ",Float64.(norm(f2-b̃, Inf)))
println("f3 diff: ",Float64.(norm(f3-c̃, Inf)))
println("Q diff: ", Float64.(norm(Q-Q̃2, Inf)))
```

A few things to note here.

If you change `contour_length` to 50 in the non-BigFloat version, it is numerically unstable.

```julia
@time E,E2,f1,f2,f3,Q = contour_integral(h,128,50)
E diff: 0.0

E2 diff: 0.0

f1 diff: 439.03407205898594

f2 diff: 8.703978181219762

f3 diff: 9.479112196568042

Q diff: 5.677563634221672e-9
```

Their default from the paper is 15, which this shows is very inaccurate

```julia
@time E,E2,f1,f2,f3,Q = contour_integral(h,128,15)
E diff: 0.0

E2 diff: 0.0

f1 diff: 0.0008651205657772458

f2 diff: 0.0009796833604201148

f3 diff: 0.017863924500895922

Q diff: 0.020912521540345154
```

At 30 it's good:

```julia
@time E,E2,f1,f2,f3,Q = contour_integral(h,128,30)

E diff: 0.0

E2 diff: 0.0

f1 diff: 7.312075489076844e-7

f2 diff: 2.2749229020835076e-8

f3 diff: 1.3929583469550427e-8

Q diff: 4.489460019019287e-13
```

which shows that their method is highly numerically unstable, or at least hard to use properly! We can see the contours with bigs and the multiprecision essentially match:

```julia
@time E,E2,f1,f2,f3,Q = big_contour_integral(h,128)

E diff: 0.0

E2 diff: 0.0

f1 diff: 3.734628920691377e-9

f2 diff: 1.3112516724168782e-9

f3 diff: 2.19973331946497e-9

Q diff: 1.699216236371553e-14
```

So the multiprecision method is simply more precise than the contour integration method, and what they used in the paper is only good up to 2 decimal places.

Then if we check the timings:

```julia
@btime E,E2,f1,f2,f3,Q = contour_integral(h,128,30)
@btime Ẽ,Ẽ2,ã,b̃,c̃,Q̃2 = multiprecision(h)
```

```julia
  30.600 ms (5236 allocations: 16.60 MiB)
  23.855 ms (373864 allocations: 15.89 MiB)
```

These quick benchmarks say the latter is more unoptimized (it's allocating at a lot more!) yet it's still faster. So the best thing to do is to reject the old MATLAB ways go forth with multiprecision algorithms!

**Comment by ChrisRackauckas** [comment]
And for future reference, the `expm` code we were playing around with

```julia
using OrdinaryDiffEq, Expokit
L = D^2; L = .01*L[2:N,2:N] # 2nd-order differentiation
L = big.(L)
A = h*big.(L)
f(t,u,du) = A_mul_B!(du,L,u)
u0 = big.([1;zeros(18)])
sols = [solve(ODEProblem(f,[zeros(i);big(1);zeros(18-i)],big.((0.0,h))),Vern9(),reltol=1e-25,abstol=1e-25)[end] for i in 0:18]
Etmp = hcat(sols...)
Float64.(Etmp)
det(Etmp) - exp(trace(A))

norm(E - Etmp,Inf)

f(t,u,du) = A_mul_B!(du,A,u)
u0 = big.([1;zeros(18)])
sol = solve(ODEProblem(f,u0,big.((0.0,h))),Vern9(),reltol=1e-30,abstol=1e-30)
sol2 = solve(ODEProblem(f,u0,big.((0.0,h))),Vern9(),reltol=1e-20,abstol=1e-20)
tmp = chbv(A,big.([1;zeros(18)]))

println(Float64.(E[1,:] - tmp))
println(Float64.(E[1,:] - sol[end]))
println(Float64.(tmp - sol[end]))
println(Float64.(sol[end] - sol2[end]))
```

finds `expm` is accurate to about `1e-15`, so using `expm` on the matrix of `Float64` is fine.

**Comment by YingboMa** [comment]
Could this work be bind with `DiffEqApproxFun.jl`? Looks like the Chebyshev grid or other discretization can be generated by `ApproxFun.jl` easily.

**Comment by ChrisRackauckas** [comment]
Yes, the test matrix could be generated with ApproxFun. But that's not the point though. The algorithm generates `a`, `b`, and `c` for any `L`, and these are the update coefficients for the exponential RK method (see the paper). 

Basically what will happen is we'll have an exponential RK method. Then people can generate linear operators with DiffEqOperators.jl or ApproxFun.jl, and then use this method on their operators to solve the time stepping PDE. So it's one part of the PDE solver, assuming the operators exist.

Exponential RK methods would make a great GSoC project BTW if anyone is interested.

**Comment by glwagner** [comment]
Is the point that the contour must enclose the eigenvalues of L? There is a comment about this after (2.7). 

I guess I'd just add that another way of saying the same thing is: choosing a "good" contour path and resolution for accurate contour integral is apparently non-trivial even for one problem and probably even more difficult to generalize, at least for non-diagonal problems. That's a great argument alone for using a multiprecision algorithm in general if its stable. Even better if its significantly faster and more accurate.

**Comment by ChrisRackauckas** [comment]
>Is the point that the contour must enclose the eigenvalues of L? There is a comment about this after (2.7).

There's more to it than that. At their value for the radius, `r=15`, it wasn't large enough to enclose the eigenvalues and thus led to errors. `r=30` works. Yay. Given their discussion, that's all there is to the story. However, if you move it to `r=50`, I showed it fails again. Miserably, like `f3 diff: 9.479112196568042`, so it's not even correct in the first decimal place. So there's not only a non-trivial lower bound, but also a non-trivial upper bound that needs to be satisfied to get the calculation right to even a few (4?) decimal places. The authors didn't even pick something in the right range. These tests show you need to be somewhere like `r in 25..35` for it to get a more than a few decimal places. So it's the combination of an upper bound with the lower bound that then makes it a very sensitive algorithm!

But at the same time, for diagonal matrices this is much more simpler and I suspect it works well pretty generally there. But this goes to show floating point is really really hard!

**Comment by ChrisRackauckas** [comment]
Implemented.

**Comment by ChrisRackauckas** [comment]
![capture](https://user-images.githubusercontent.com/1814174/35989884-411f3fee-0cb7-11e8-8d93-83ea9a4c3c5d.PNG)

![capture2](https://user-images.githubusercontent.com/1814174/35989888-4230242a-0cb7-11e8-8f82-cff416444179.PNG)

**Comment by ChrisRackauckas** [comment]
![capture](https://user-images.githubusercontent.com/1814174/35991438-12ffb882-0cbc-11e8-9ee4-18ed61f12e70.PNG)
![capture2](https://user-images.githubusercontent.com/1814174/35991440-13220798-0cbc-11e8-81aa-0460601e5285.PNG)
![capture3](https://user-images.githubusercontent.com/1814174/35991442-133c6f8e-0cbc-11e8-9199-b90d402baee3.PNG)

**Comment by ChrisRackauckas** [comment]
![capture](https://user-images.githubusercontent.com/1814174/35991506-3d6d8716-0cbc-11e8-824f-29becfbca983.PNG)

**Comment by ChrisRackauckas** [comment]
![capture](https://user-images.githubusercontent.com/1814174/35991683-cc219d94-0cbc-11e8-9538-6e8ca2df1609.PNG)
