### ISSUE TITLE
reinit! does not clear integrator.sol.interp.timeseries

### ISSUE THREAD

**Issue by tkf** [JuliaDiffEq/OrdinaryDiffEq.jl#246]
In my https://github.com/tkf/LyapunovExponents.jl/pull/1, I realized that re-using ODEIntegrator causes a problem when using different `u0`.  It seems that the integration result is correct.  Only the recording into the solution object is not happening correctly.

The hack I found is to reset `integrator.sol.interp.timeseries` manually.  I didn't go deep in the code to see if that's the good way to do it.  But if so, it's very trivial to fix `reinit!`.

Here is the code to demonstrate the issue and the hack.  The assert should fail unless you uncomment `empty!(integrator.sol.interp.timeseries)` and `push!(integrator.sol.interp.timeseries, u1)`:

```julia
using DifferentialEquations

f(t, u, du) = (du .= -u)
u0 = [10.0]
t0 = 0
t1 = 1.0
t2 = 2 * t1

# Solve the ODE in one go:
long_ode = ODEProblem(f, copy(u0), (t0, t2))
long_sol = solve(long_ode)
times = linspace(t0, t2, 100)
long_data = hcat(map(long_sol, times)...)

half_ode = ODEProblem(f, copy(u0), (t0, t1))
alg, extra_kwargs = default_algorithm(half_ode)
integrator = init(half_ode, alg)

solve!(integrator)
u1 = integrator.sol[end]
first_data = [integrator.sol(t) for t in times if t < t1]

# Continue solving the ODE for tspan = "(t1, t2)"; OK, since t2 = 2 * t1
reinit!(integrator, u1)
# Without the following lines, `@assert` below does not work:
# empty!(integrator.sol.interp.timeseries)
# push!(integrator.sol.interp.timeseries, u1)
solve!(integrator)
second_data = [integrator.sol(t - t1) for t in times if t >= t1]

cat_data = hcat(vcat(first_data, second_data)...)

# It is easy to see if you plot it (but don't use `plot(integrator)`):
# using Plots
# plot(integrator.sol)

@assert isapprox(cat_data, long_data;
                 rtol=integrator.opts.reltol,
                 atol=integrator.opts.abstol)
```

checked with
```
julia> Pkg.status("OrdinaryDiffEq")
 - OrdinaryDiffEq                2.36.0
```

**Comment by ChrisRackauckas** [comment]
`integrator.sol.interp.timeseries` should just be an alias to `integrator.sol.u`. The latter is reset during the `reinit!` by simply `resize!`:

https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/src/integrators/integrator_interface.jl#L190-L206

That must not be acting correctly with aliasing and should be double checked. I think I noticed this in a currently private repo. 

More generally, we need to find out if our approach here is any good. Resetting like this can be a little wasteful to memory if we know we're just going to refill it. There's definitely a better and safer implementation to be had here.

**Comment by tkf** [comment]
Thanks. I see.

If I understand correctly, `Array{T, 1}` stores length and "capacity" (= size of the underlying memory block) separately, right?  I wish Julia expose some APIs about capacity. If we can tell "resize the length, but not the capacity" then it's super easy to solve this (because all the hard implementation details goes into the language core).

**Comment by ChrisRackauckas** [comment]
The idea is to implement a memory buffer type for Julia, and then build strings, arrays, and new Big types based off of that primitive. That didn't make it into v1.0 though, but it's what we really need for this.

**Comment by tkf** [comment]
That sounds cool.  Can't wait Julia 2.0 :)

**Comment by tkf** [comment]
Maybe related.  This is from discussion about my script at https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/pull/256#issuecomment-366857675 on gitter:

> So
> 
> ```julia
> step!(integrator1, t_half)
> set_t!(integrator1, integrator1.t)
> @show integrator1.u
> @show integrator1.sol.u
> solve!(integrator1)
> @show integrator1.sol.t[1]
> @show integrator1.sol.u[1]
> ```
> 
> prints
> 
> ```julia
> integrator1.u = 3.874272723202465
> integrator1.sol.u = [0.5]
> integrator1.sol.t[1] = 0.0
> integrator1.sol.u[1] = 0.5
> ```
> I suppose this is due to
> 
> ```julia
>   if erase_sol  # = true
>     if integrator.opts.save_start  # = true
>       resize_start = 1
>     else
>       resize_start = 0
>     end
>     resize!(integrator.sol.u,resize_start)
>     resize!(integrator.sol.t,resize_start)
> ```
> 
> in `reinit!`?
