### ISSUE TITLE
Suggestion: allow DiscreteProblem.tspan::Tuple{Int,Int}

### ISSUE THREAD

**Issue by tkf** [JuliaDiffEq/OrdinaryDiffEq.jl#251]
Since OrdinaryDiffEq.jl can already solve discrete dynamical systems, why not allow `tspan::Tuple{<:Integer, <:Integer}`?  That would make the following code work.  Also, why not make `FunctionMap(scale_by_time=false)` the default *when* `tspan::Tuple{<:Integer, <:Integer}`?

```julia
using DifferentialEquations

function henon_map!(u_next, u, _p, t)
    u_next[1] = 1 + u[2] - 1.4 * u[1]^2
    u_next[2] = 0.3 * u[1]
end

prob = DiscreteProblem(henon_map!, [0.5, 0.5], (0, 100))
# prob = DiscreteProblem(henon_map!, [0.5, 0.5], (0.0, 100.0))  # this works
sol = solve(prob, FunctionMap(scale_by_time=false))

using Plots
scatter(sol, vars=(1, 2))
```

**Comment by ChrisRackauckas** [comment]
There's no problem with integer time spans. 

https://github.com/JuliaDiffEq/DiffEqBase.jl/blob/master/src/problems/discrete_problems.jl#L4-L7

Also, `scale_by_time=false` is the default. 

https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/src/algorithms.jl#L19

**Comment by tkf** [comment]
I mean, it seems that `init` doesn't accept integer tspan at the moment.

```
ERROR: LoadError: InexactError()
Stacktrace:
 [1] convert at ./rational.jl:85 [inlined]
 [2] Int64(::Rational{Int64}) at ./sysimg.jl:77
 [3] init(::DiffEqBase.DiscreteProblem{Array{Float64,1},Int64,true,Void,#henon_map!,Void}, ::OrdinaryDiffEq.Discrete{true,false}, ::Array{Any,1}, ::Array{Any,1}, ::Array{Any,1}, ::Type{Val{true}}) at /home/tkf/.julia/v0.6/OrdinaryDiffEq/src/solve.jl:53
 [4] #solve#1308(::Array{Any,1}, ::Function, ::DiffEqBase.DiscreteProblem{Array{Float64,1},Int64,true,Void,#henon_map!,Void}, ::OrdinaryDiffEq.Discrete{true,false}, ::Array{Any,1}, ::Array{Any,1}, ::Array{Any,1}, 
::Type{Val{true}}) at /home/tkf/.julia/v0.6/OrdinaryDiffEq/src/solve.jl:6
 [5] solve(::DiffEqBase.DiscreteProblem{Array{Float64,1},Int64,true,Void,#henon_map!,Void}, ::OrdinaryDiffEq.Discrete{true,false}) at /home/tkf/.julia/v0.6/OrdinaryDiffEq/src/solve.jl:6
 [6] include_from_node1(::String) at ./loading.jl:576
 [7] include(::String) at ./sysimg.jl:14
 [8] src(::String) at /home/tkf/.juliarc.jl:77
while loading tspan.jl, in expression starting on line 10
```

**Comment by tkf** [comment]
Also, I need to pass `FunctionMap(scale_by_time=false)` because otherwise the map is ignored and the solution is filled with the copy of `u0`. Just to be clear, the following code passes.

```
using DifferentialEquations

function henon_map!(u_next, u, _p, t)
    u_next[1] = 1 + u[2] - 1.4 * u[1]^2
    u_next[2] = 0.3 * u[1]
end

prob = DiscreteProblem(henon_map!, [0.5, 0.5], (0.0, 100.0))
sol = solve(prob)
@assert sol[end] == [0.5, 0.5]
```

**Comment by ChrisRackauckas** [comment]
Alright. Yes, the behavior you want is intended behavior. It should be made "truly intended" by getting fixed and adding some tests. Also, I am thinking of doing away with `Discrete` because of the overlap with Distributions.jl, and instead just having it all be `FunctionMap`. Objections?

**Comment by tkf** [comment]
I actually didn't know why `apply_map=false` was there (just guessing that it was for `dt -> 0` or something) and why it was related to Distributions.jl, so, no objections :)

**Comment by Datseris** [comment]
@ChrisRackauckas Maybe you want to consider Using `DiscreteProblem` from `DynamicalSystemsBase` ? AFter #23 there is the fundamental structure `DiscreteProblem` with very well tested `evolve!` and `evolve` methods, and allows for both in place and out of place evolution. It follows identical syntax with `ODEProblem`, but **does not use** time in the constructor. 

(As a research who was worked many many times with discrete systems I can tell you that having ``t_n`` is very intuitive in my field.)

You don't have to use it in DiffEq, but you can simply link your docs to mine, after my docs are online of course.

**Comment by ChrisRackauckas** [comment]
@Datseris I don't get your suggestion, though thanks for reminding me of this issue. I made the change to `FunctionMap` (and throw a warning for `Discrete()` now). I'll find out what's going on with integers since I think I ran into that while changing some tests.

**Comment by ChrisRackauckas** [comment]
https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/commit/7bdaca828db2b092eaa290713d28d78549ca9aff

**Comment by Datseris** [comment]
There seems to be just a bit more tweaking necessary here. (Or I just don't understand how to use `typemax`).

Here is the MWE:
```julia
# Pkg.checkout("OrdinaryDiffEq")
using OrdinaryDiffEq
@inline henon_eom(x, p, n) = SVector{2}(1.0 - p[1]*x[1]^2 + x[2], p[2]*x[1])
u0h = zeros(2)
ph = [1.4, 0.3]
tspan = (0, typemax(Int)-1)
prob = DiscreteProblem(henon_eom, SVector{2}(u0h), tspan, ph)
integ = init(prob, FunctionMap())
```
The above gives inexact error in the line `round(Int,float((tspan[2]-tspan[1])/dt),RoundUp)`. When giving `tspan = (0, 100)` it works.

To my surprise, when giving `tspan = (0, Int(1e12))` it gives an `OutOfMemoryError()` which results from `    sizehint!(timeseries,steps+1)`... 

I guess none of the 2 "unwanted behaviors" can be cured.

**Comment by Datseris** [comment]
EDIT: You get `outofmemory` even with `save_Everystep=false`

**Comment by ChrisRackauckas** [comment]
Fixed on master, at least with `save_everystep=false`. With `save_everystep=true` it correctly throws a conversion error because the number of steps is more than the number of 64-bit integers which would then having trouble indexing in a normal array anyways (and would never fit on a computer...), and 1e12 + 1 throws an out of memory error because a vector of length `2e12` is never going to fit on your computer.
