### ISSUE TITLE
Support resetting time?

### ISSUE THREAD

**Issue by tkf** [JuliaDiffEq/OrdinaryDiffEq.jl#253]
Consider solving ODEs with a periodic external force for long period of time.  If you choose a large `tspan`, `sin(t)` becomes inaccurate at some point.  In this case, if there is a way to reset the time tracked by the integrator without touching its caches like `dt` for adaptive methods, I can just set `tspan` to be the (integer multiple of the) period of the external oscillator and then keep calling `solve!`.  This way, `t` can be kept around 1.0 so that there is no loss in the accuracy.

Note that `eps(1e10) ≈ 1.9e-6` which is comparable to the default `abstol = 1e-6`.  For solving some crazy chaotic system with long transient or convergence properties, I think it is imaginable that some researchers want to simulate for that long amount of time.  Also, sometimes you draw so-called bifurcation diagram by slowly varying parameters.  In such case, the total simulated time can be even longer.

Just to be a bit more precise, what I want to achieve is to do something like

```julia
for _ in 1:N
    reinit!(integrator, integrator.sol[end])
    solve!(integrator)
    ... do something with the result ...
end
```

but without resetting `dt` and other algorithm-related caches (if any).

**Comment by ChrisRackauckas** [comment]
>but without resetting dt and other algorithm-related caches (if any).

You can do that already using the keyword options in `reinit!`. The issue though is that overlapping times will destroy the interpolation: it just won't know what to do. I'm not sure if that can be handled though, but if you're not using it that's fine.

**Comment by tkf** [comment]
For my use-case, I have integrator with `save_everystep=false` so not possible to do interpolation is OK.  So, to do that I just need to pass `false` to `re*_*` flags, like this?

```julia
reinit!(integrator, integrator.sol[end],
        reset_dt = false,
        reinit_callbacks = false,
        reinit_cache = false)
```

(I wasn't sure if it works, since integrator could have saved the last `t` in the cache and comparing to the current one, or something like that.  If that's the cas if the new `t` after `reinit!` is before that last `t`, the integrator could go haywire. Anyway, if it is not the problem then that's great!)

**Comment by ChrisRackauckas** [comment]
yup that should work.

**Comment by tkf** [comment]
Thanks!  Another related question: in adaptive method, is there some overhead for integrator to try arriving exactly at `tspan[2]` for adaptive method?  I mean, if I don't care with the precision of the end time, is it valid way?:

```julia
function surpass!(integrator, t1)
   t0 = integrator.t
    while integrator.t < t1
        step!(integrator)
    end
    return integrator.t - t0
end

t0, t1 = integrator.sol.prob.tspan
while not done yet
    integrator.t = t0
    actual_delta_t = surpass!(integrator, t1)
    some operations here with actual_delta_t and integrator.u
end
```

I can benchmark it myself to see if it's giving me any performance improvement, but I just wanted to see if the design of DifferentialEquations.jl is compatible with it.  Especially, I want to know if it has memory leak issue.

BTW, since DifferentialEquations.jl has tons of low-level stepping controls, does it make sense to have `surpass!` and `set_t!(integrator, t) = (integrator.t = t)`?  I mean, I can be more confident if it's in the API.  I'll happily open a PR.

**Comment by ChrisRackauckas** [comment]
>is there some overhead for integrator to try arriving exactly at tspan[2] for adaptive method? I mean, if I don't care with the precision of the end time, is it valid way?:

The overhead doesn't exist. I mean, there's the overhead of shortening the time step to make it hit `tspan[2]` exactly, so if you add tstops in you can shorten time steps to make it take more, but that's really it. But as long as there's another tstop, there's no difference in the calculation:

https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/src/integrators/integrator_utils.jl#L68

`surpass!` and `set_t!` are good ideas. I think a `saveat_iterator` would be nice to have too.

**Comment by tkf** [comment]
The overhead I was trying to ask was for to get `u(tspan[2])`.  But this is probably just done by interpolating `integrator.uprev` and `integrator.u`?

I was wondering this because I've read:

> tstops: Denotes extra times that the timestepping algorithm must step to. This should be used to help the solver deal with discontinuities and singularities, since **stepping exactly at the time of the discontinuity will improve accuracy**.
>
> --- http://docs.juliadiffeq.org/latest/basics/common_solver_opts.html#Output-Control-1

So I thought the integrator tries to be accurate at the given time points, like by making `dt` progressively small or doing binary search or something.  But it's already accurate up to the given tolerance so that would be handled by the interpolation?


> `saveat_iterator`

How about `tstop_iterator!`?  I'll need it for memory efficiency.

**Comment by ChrisRackauckas** [comment]
>How about tstop_iterator!? I'll need it for memory efficiency.

Isn't that just the same as setting `advance_to_tstop=true` and using the iterator?

>The overhead I was trying to ask was for to get u(tspan[2]).

That's never interpolated since `tspan[2]` is a `tstop` so it will not be stepped over.

>So I thought the integrator tries to be accurate at the given time points, like by making dt progressively small or doing binary search or something. But it's already accurate up to the given tolerance so that would be handled by the interpolation?

I'm confused at what your confusion is about. For `tstops`, it will shrink `dt` to not go over a `tstop`. You have a step of `dt`, it checks if `t+dt > tstop`, and if it is, it sets `dt = t-tstop` (well, there needs to be a floating point correction but ignore that). The reason is because it cannot assume that it can interpolate over it (ex: a discontinuity can occur at a `tstop`). One step of doing this is about the same cost as stepping over and interpolating (interpolating is relatively cheap, especially intermediate interpolations which don't need to search the time array), but its cost builds up because it means you have a smaller effective `dt`. 

So, when @Datseris asks for `saveat=0.001` all the time, what's normally going on is something like `dt=2.37`, so then it interpolates at each past point to build up the solution array (without any extra derivative calls) and then does the next step. If he did tstops for each of them, then, since the error is low enough that `dt > 0.001` in any of the steps, what will happen if he'd effectively get `dt = 0.001` and that would be slow because taking steps is a lot more computationally intensive than the intermediate interpolations.

**Comment by tkf** [comment]
Thanks.  You clarify my confusion without understanding my confusion.  I started being confused on why I was confused.

I guess then the drop in the performance (= walltime / dt) would be the truanted step `t + dt - tstop` that the integrator could have advanced if there is no `tstop`. Though that's non-negligible only when `tspan[2] - tspan[1]` is comparable to the average `dt`.


> > How about tstop_iterator!? I'll need it for memory efficiency.
>
> Isn't that just the same as setting advance_to_tstop=true and using the iterator?

Ah, yes.  Thanks, I didn't notice the combination of that option and iterator interface.

**Comment by ChrisRackauckas** [comment]
>I guess then the drop in the performance (= walltime / dt) would be the truanted step t + dt - tstop that the integrator could have advanced if there is no tstop.

Basically. What I am calling the efficiency is the time to get to the end at the user's tolerance. Using tstops will make it take smaller steps, so it will be more accurate and take longer, but it will be more accurate than the user asked for so in some sense that's not the right way to work towards the goal.

**Comment by tkf** [comment]
Usually I'm interested in long-term behavior and in that case, the actual `tspan[2]` is not very meaningful.  That's why I wanted something like `surpass!`.  But I see that when the tspan and other tstops are meaningful then you wouldn't call it an overhead.  I didn't mean that this was the overhead for everyone.
