### ISSUE TITLE
Conversion of optional value for solve

### ISSUE THREAD

**Issue by ccontrer** [JuliaDiffEq/OrdinaryDiffEq.jl#27]
The `maxiters` option for `solve` receives an integer. One correct instruction is
```
solve(prob, maxiters=Int(1e6))
```
I was biased to use `1e6` but this gives a matching method error that is not informative. Conversion to integer and appropriate massage could help.
Cheers.

**Comment by ChrisRackauckas** [comment]
This has been fixed.
