### ISSUE TITLE
Complex time parameters

### ISSUE THREAD

**Issue by orswan** [JuliaDiffEq/OrdinaryDiffEq.jl#28]
It appears that `solve` sometimes produces complex time parameters.  Here is a sample that illustrates the issue:

    # Test.jl
    module Test
    using DifferentialEquations

    function hamiltonian(q::Real,U::Real)
        return SymTridiagonal([(q+k)^2 for k=-10.:10.],fill(U/2.,(20,)))
    end

    function solver(U::Real=1.)
        function D(t,u)
            println("In D")
            println(t)
            return -im*hamiltonian(t,U)*u
        end
        u0 = complex([-10.:10.;])
        prob = ODEProblem(D,u0,promote(0.,1.))
        sol = solve(prob,dt=1./100.)
        return prob,sol
    end

    end

The println calls show what time parameter is being passed to the derivative function `D`.  The details of the `hamiltonian` function are unimportant, except that it expects to get real arguments.  

You can fix the problem by hand by only passing the real part of the time parameter to `hamiltonian`, as follows:

    # Test.jl
    module Test
    using DifferentialEquations

    function hamiltonian(q::Real,U::Real)
        return SymTridiagonal([(q+k)^2 for k=-10.:10.],fill(U/2.,(20,)))
    end

    function solver(U::Real=1.)
        function D(t,u)
            println("In D")
            println(t)
            return -im*hamiltonian(real(t),U)*u
        end
        u0 = complex([-10.:10.;])
        prob = ODEProblem(D,u0,promote(0.,1.))
        sol = solve(prob,dt=1./100.)
        return prob,sol
    end

    end

Another problem in this latter example, which is apparently related to the above issue, is that plotting the solution fails:

    julia> p,s = Test.solver();

    julia> plot(s)
    ERROR: MethodError: no method matching isless(::Float64, ::Complex{Float64})
    Closest candidates are:
      isless(::Float64, ::Float64) at float.jl:283
      isless(::AbstractFloat, ::AbstractFloat) at operators.jl:40
      isless(::Real, ::AbstractFloat) at operators.jl:41
      ...
     in expand_extrema!(::Plots.Extrema, ::Complex{Float64}) at C:\Users\swan\.julia\v0.5\Plots\src\axes.jl:239
     in expand_extrema!(::Plots.Axis, ::Array{Complex{Float64},1}) at C:\Users\swan\.julia\v0.5\Plots\src\axes.jl:262
     in expand_extrema!(::Plots.Subplot{Plots.PlotlyBackend}, ::Dict{Symbol,Any}) at C:\Users\swan\.julia\v0.5\Plots\sr
    c\axes.jl:289
     in _expand_subplot_extrema(::Plots.Subplot{Plots.PlotlyBackend}, ::Dict{Symbol,Any}, ::Symbol) at C:\Users\swan\.j
    ulia\v0.5\Plots\src\pipeline.jl:361
     in _process_seriesrecipe(::Plots.Plot{Plots.PlotlyBackend}, ::Dict{Symbol,Any}) at C:\Users\swan\.julia\v0.5\Plots
    \src\pipeline.jl:392
     in _plot!(::Plots.Plot{Plots.PlotlyBackend}, ::Dict{Symbol,Any}, ::Tuple{DiffEqBase.ODESolution{Array{Array{Comple
    x{Float64},1},1},Array{Float64,1},Array{Array{Array{Complex{Float64},1},1},1},DiffEqBase.ODEProblem{Array{Complex{F
    loat64},1},Float64,false,Test.#D#3{Float64}},OrdinaryDiffEq.Tsit5,OrdinaryDiffEq.InterpolationData{Test.#D#3{Float6
    4},Array{Array{Complex{Float64},1},1},Array{Float64,1},Array{Array{Array{Complex{Float64},1},1},1},OrdinaryDiffEq.T
    sit5ConstantCache{Complex{Float64}}}}}) at C:\Users\swan\.julia\v0.5\Plots\src\plot.jl:227
     in plot(::DiffEqBase.ODESolution{Array{Array{Complex{Float64},1},1},Array{Float64,1},Array{Array{Array{Complex{Flo
    at64},1},1},1},DiffEqBase.ODEProblem{Array{Complex{Float64},1},Float64,false,Test.#D#3{Float64}},OrdinaryDiffEq.Tsi
    t5,OrdinaryDiffEq.InterpolationData{Test.#D#3{Float64},Array{Array{Complex{Float64},1},1},Array{Float64,1},Array{Ar
    ray{Array{Complex{Float64},1},1},1},OrdinaryDiffEq.Tsit5ConstantCache{Complex{Float64}}}}) at C:\Users\swan\.julia\
    v0.5\Plots\src\plot.jl:46

**Comment by ChrisRackauckas** [comment]
The first is fixed on master. 

The second is because Plots.jl doesn't know how to plot complex numbers. I have an idea for how to extend the plot recipe here, but that's a separate issue.
