### ISSUE TITLE
Can't use the time variable inside the function that describes the dynamic equation

### ISSUE THREAD

**Issue by ronisbr** [JuliaDiffEq/OrdinaryDiffEq.jl#300]
Hi @ChrisRackauckas ,

How are you?

I was trying to use OrdinaryDiffEq.jl to solve a problem and it turns out that the variable `t` inside the dynamic equation function is returning `nothing`. See this simple code:

```julia
function dyn_eq(du,u,t,p)
    du .= [0 1;0 0]*u + [0;1]*t
    nothing
end

x0 = [0.;0.]

tf = 10.
tstops = collect(0:1.0:tf)

prob = ODEProblem(dyn_eq, x0, (0.0, tf))
sol = solve(prob, Tsit5(), tstops=tstops)
```

I am getting this error:

    ERROR: LoadError: MethodError: no method matching *(::Array{Int64,1}, ::Void)

When I print `t`, then `nothing` is returned. Am I doing something wrong?

**Comment by SebastianM-C** [comment]
I think the order of the parameters is `f(du,u,p,t)`.

**Comment by ronisbr** [comment]
Oh, that is embarrassing :) Thanks!

**Comment by SebastianM-C** [comment]
No problem :)
