### ISSUE TITLE
Bulirsch–Stoer and other extrapolation algorithms

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/OrdinaryDiffEq.jl#312]
Good for very precise integrations (BigFloats) and can be parallelized.

**Comment by ChrisRackauckas** [comment]
Hairer I describes ODEX, a GBS method.

https://en.wikipedia.org/wiki/Bulirsch%E2%80%93Stoer_algorithm
https://link.springer.com/article/10.1007%2FBF01418332
https://link.springer.com/article/10.1007%2FBF01390211

Then for implicit, there is SEULEX and SODEX, based on linearly-implicit Euler or Midpoint.

**Comment by ChrisRackauckas** [comment]
These algorithms are interesting since they have a structure that can be easily multithreaded and parallelized. It would be interesting to do some implementations of these to see how well they do on different computational architectures. Here's a writeup saying a simple parallelized ODEX can do better than DOP853:

https://arxiv.org/abs/1305.6165

Of course, non-parallel versions need to come first.

**Comment by bjodah** [comment]
If Bulirsch-Stoer methods are implemented I'd like to mention that I've had good experience using the semi-implicit variation due to [Bader & Deufelhard](https://link.springer.com/article/10.1007/BF01418331) implemented [GNU scientific library](http://git.savannah.gnu.org/cgit/gsl.git/tree/ode-initval2/bsimp.c).

**Comment by ChrisRackauckas** [comment]
The non-stiff ones are done. Now just the implicit ones.

**Comment by ChrisRackauckas** [comment]
SEULEX is implemented here: https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/pull/797

**Comment by ChrisRackauckas** [comment]
with https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/pull/851 SODEX, this is complete. A PR will make SEULEX and SODEX multithreaded shortly as well, and we'll publish how this parallelism is done and those results :).

**Comment by ChrisRackauckas** [comment]
Another reference on parallelism: https://www.tandfonline.com/doi/pdf/10.1080/08905459408905222?casa_token=3hSF-p506WwAAAAA:GOH5Ac1XKAGZmdcBevwC0pzsNi2-ttw2b1C9phh_59NQC9g-E8SRxppDXdG562UixT6TbKuZVqI
