### ISSUE TITLE
Properties of CompositeAlgorithm

### ISSUE THREAD

**Issue by devmotion** [JuliaDiffEq/OrdinaryDiffEq.jl#317]
I'm wondering whether the properties of `CompositeAlgorithm` defined in https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/src/alg_utils.jl should be more consistent and/or have to be extended. More precisely, I'm interested in why some methods such as https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/src/alg_utils.jl#L5 refer to the properties of the current algorithm, whereas others such as https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/src/alg_utils.jl#L197 refer to the first algorithm. Shouldn't properties of a `CompositeAlgorithm` always refer to the properties of the current algorithm? Additionally, many methods are not defined for `CompositeAlgorithm` specifically, e.g. `fsal_typeof`, `is_implicit`, and many more will only return defaults for `OrdinaryDiffEqAlgorithm`. Moreover, it's a bit surprising that in https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/src/alg_utils.jl#L34 a method is defined for `ODECompositeAlgorithm` whereas otherwise all definitions only apply to `CompositeAlgorithm`.

**Comment by ChrisRackauckas** [comment]
>Shouldn't properties of a CompositeAlgorithm always refer to the properties of the current algorithm? 

Yes. This should get updated. 

>Additionally, many methods are not defined for CompositeAlgorithm specifically, e.g. fsal_typeof, is_implicit, and many more will only return defaults for OrdinaryDiffEqAlgorithm

Those are needed. 

>Moreover, it's a bit surprising that in https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/src/alg_utils.jl#L34 a method is defined for ODECompositeAlgorithm whereas otherwise all definitions only apply to CompositeAlgorithm.

Yeah, I wasn't sure at first whether there would be multiple composite algortihms. I think at this point that everything will be `CompositeAlgorithm` with a choice function, so these should probably all be on the concrete type.

**Comment by ChrisRackauckas** [comment]
Actually, I remember why I did this. `CompositeAlgorithm` isn't thread-safe if you use `current_alg` inside of it. All `current_alg` choices should be part of the `cache` instead. That makes the traits much harder though, and should be picked on an all basis?
