### ISSUE TITLE
@ode_exit_conditions

### ISSUE THREAD

**Issue by tkf** [JuliaDiffEq/OrdinaryDiffEq.jl#318]
`step!` is now

https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/79a2e1478263f5f030eafdcb2cf1ea4eb40d5b05/src/iterator_interface.jl#L1-L19

and `solve!` is

https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/79a2e1478263f5f030eafdcb2cf1ea4eb40d5b05/src/solve.jl#L334-L347

Should we call `@ode_exit_conditions` (or `check_error!`) before `perform_step!` in `step!` as well?

It's somewhat related to what @devmotion was mentioning in https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/pull/316#issuecomment-381069870

**Comment by ChrisRackauckas** [comment]
Oh yes, we probably should, but not while rejection looping (12-15)

**Comment by tkf** [comment]
A bit of awkwardness with this PR is that `step!` returns a solution when it hits a non-success exit condition whereas it returns `nothing` when success.

**Comment by ChrisRackauckas** [comment]
should it always return the current solution then?

**Comment by tkf** [comment]
What `step!` returns is not documented so I guess it's OK.  I noticed it so I thought I'd just mention it.  Does Julia have type-instability problem even when returned value is not used?

If you want the return value to be consistent, I suggest to modify `@ode_exit_conditions` to accept a return value expression and use it like `@ode_exit_conditions(nothing)`.  `step!(integrator, dt)` returns the actual step taken so returning a solution only for the case `step!(integrator)` is confusing, I think.

**Comment by ChrisRackauckas** [comment]
>Does Julia have type-instability problem even when returned value is not used?

It does slow it down a tiny amount on v0.6... I think it would be best to have this just return nothing.

>step!(integrator, dt) returns the actual step taken so returning a solution only for the case step!(integrator) is confusing, I think.

I agree, that does make it confusing. Returning the solution shouldn't be done then.
