### ISSUE TITLE
Force simulation to stop

### ISSUE THREAD

**Issue by ronisbr** [JuliaDiffEq/OrdinaryDiffEq.jl#33]
Hi @ChrisRackauckas,

I have a veeery long simulation that I am analyzing by Monte Carlo. I am interested only on the convergence time, which I can compute. In order to save execution time, is there any way to force the solver to stop if a variable becomes `true`?

**Comment by ronisbr** [comment]
My approach is the create a callback and use `terminate!(integrator)`. I am not sure if this is the right approach.

**Comment by ChrisRackauckas** [comment]
Yes, that is the right approach.

**Comment by ronisbr** [comment]
Hi @ChrisRackauckas ,

The problem is that in this case with my code the last sampling step is not stored. For example, if I use a boolean variable to stop the simulation, I did not see the sampling step with this variable `true`.

I created a gist with a sampling code:

https://gist.github.com/ronisbr/9dfadf0014b00422f708fb3d3d8ba004

Basically, I have a `stop` variable that becomes true if `t>=15.0`. In this case, a callback is activated and `terminate!` is called. However, if you look at `sol[end].stop`, it is `false`. But I thought that this variable must be true. Am I doing something wrong?

**Comment by ChrisRackauckas** [comment]
Bug. It was saving via the interpolation from the previous value, which misses the discrete change. Fixed by https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/commit/90b16c79b079a5deb632db2fd3b768607c6db6cf

**Comment by ronisbr** [comment]
@ChrisRackauckas you are very fast :)

Thanks for the wonderful wonderful work with this package.

Btw, I am preparing a blog post in my website about how use julia + OrdinaryDiffEq to simulate discrete/continuous systems for Control studies. This package and your callback implementation is just unseen IMHO. It was the very first time that I could easily move from Simulink to a programming language! Thanks!

**Comment by ronisbr** [comment]
I forgot to mention that this commit indeed fixed my problem :)
