### ISSUE TITLE
Verify the correctness of CompositeAlgorithm's interpolation

### ISSUE THREAD

**Issue by YingboMa** [JuliaDiffEq/OrdinaryDiffEq.jl#345]
This problem is brought up in https://github.com/JuliaDiffEq/DiffEqCallbacks.jl/issues/42 .

**Comment by ChrisRackauckas** [comment]
https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/commit/b7f744f5e6bf0096b9520556ca0ec7c946394def
