### ISSUE TITLE
Limit a state variable using callbacks

### ISSUE THREAD

**Issue by ronisbr** [JuliaDiffEq/OrdinaryDiffEq.jl#35]
Hi @ChrisRackauckas ,

I was thinking about control problems using this package like you asked me. Currently, I can't think about a model that will make things easier to implement like your models. However, there are some interesting points we can adjust for control system simulations.

Today, I was wondering how can I simulate a limit to a variable using callbacks. For example, let's consider the example about the moving particle I posted in my blog. Maybe I want to define a maximum allowed velocity. I tried to implement this with callbacks using the following code:

```julia
# Condition function.
function condition_vel_limit(t,u,integrator)
    vl - abs(u[2])
end

function vel_limit!(integrator)
    integrator.u[2] = sign(integrator.u[2])*vl-0.001
end
```
where `vl` is the velocity limit.

It is working fine but notice the `0.001`. Without that the callback does not work. I suspect it is because the way how the condition function is evaluated. The full source code is here:

https://gist.github.com/ronisbr/ff3e8899cb19926d0d3fb9cedd5d0c8a

The result I got is:

![figure](https://cloud.githubusercontent.com/assets/1068295/22700967/70f73e90-ed43-11e6-8797-7ae0ae4d6474.png)

Is there a better way to implement this limit using callbacks?

**Comment by ChrisRackauckas** [comment]
I think I would do it with a "blank" `affect` function where the condition just makes sure you hit the point of discontinuity (in the derivative of the dynamics equation), and change the dynamic equation to limit the velocity. I'll write an example when I get back.

**Comment by ChrisRackauckas** [comment]
Here's what I mean:

https://gist.github.com/ChrisRackauckas/716251371b60add1793430002f57c96a

Instead of forcing it back to two all of the time, set the acceleration to 0 if the velocity is 2 and the acceleration would be positive. This incorporates the effect into the model.

**Comment by ronisbr** [comment]
Thanks @ChrisRackauckas 

I will need to modify it a little bit, because the control loop must not have the information about the acceleration limit. But I understood the idea :)
