### ISSUE TITLE
Warning message about method being overwritten

### ISSUE THREAD

**Issue by ronisbr** [JuliaDiffEq/OrdinaryDiffEq.jl#368]
Hi!

Today, after installing **OrdinaryDiffEq.jl**, I am seeing the following message every time I type `using OrdinaryDiffEq`:

```
WARNING: Method definition (::Type{NLSolversBase.OnceDifferentiable{TF, TDF, TX} where TX where TDF where TF})(Any, AbstractArray{T, N} where N where T, AbstractArray{T, N} where N where T) in module NLSolversBase at /Users/ronan.arraes/.julia/v0.6/NLSolversBase/src/objective_types/oncedifferentiable.jl:114 overwritten in module NLsolve at /Users/ronan.arraes/.julia/v0.6/NLsolve/src/objectives/autodiff.jl:2.
```

In my examples, I have not seeing any computation problems though.

**Comment by ChrisRackauckas** [comment]
@pkofod

**Comment by pkofod** [comment]
Did Pkg tell you your metadata was out of date and you should pkg.update? Because this should have Bern fixed

**Comment by pkofod** [comment]
It think it's because you have an outdated METADATA copy, as this was previously caused by an incorrect `REQUIRE` file in `NLsolve` that has since been resolved. I cannot reproduce locally. Please run `Pkg.update()` to fix this.

**Comment by ronisbr** [comment]
Hi @pkofod ,

I have indeed run `Pkg.update()` thousand of times, and I was seeing the problem. However, after deleting completely my `v0.6` directory and installing everything again, I can no longer see this issue.

Thanks! I will do this next time before reporting a bug.

**Comment by pkofod** [comment]
> Thanks! I will do this next time before reporting a bug.

You shouldn't have to delete your directory every time, but good to know it works!
