### ISSUE TITLE
Optimization in VCABM

### ISSUE THREAD

**Issue by sipah00** [JuliaDiffEq/OrdinaryDiffEq.jl#380]
Following optimizations can be done to improve the performance of `VCABM`.
1. Reuse variable coefficients when `curr_step_size/last_step_size ~ 1`
2. Expansion of `phi` vectors can be optimized.
3. On three or four consecutive step rejections, reset order to one.
current benchmarks on Pleiades and linear ODE.
![plotple](https://user-images.githubusercontent.com/23627932/41275238-d6d9aece-6e3d-11e8-87ac-c751d2b5f32c.png)
![plot_l](https://user-images.githubusercontent.com/23627932/41275273-f63c9a60-6e3d-11e8-86f6-39f327133f19.png)

**Comment by ChrisRackauckas** [comment]
>On three or four consecutive step rejections, reset order to one.

Why would this be helpful?

**Comment by ChrisRackauckas** [comment]
Can you use `SavingCallback` to recreate the Hairer figures that show how order and time step changes over the course of the integrations?

**Comment by ChrisRackauckas** [comment]
Also, can you post the flame graphs you get from profiling?

**Comment by sipah00** [comment]
Reset order to one; we have seen many rejections at low tolerance, due to this in every rejection, variable coefficients are being calculated for the higher order which takes time. Also, next step size will be decreased, I am not sure, it is a good idea or not.

**Comment by ChrisRackauckas** [comment]
I'm not sure that's a good idea. The adaptivity should never been changing so much that it should be necessary. We should instead tweak the adaptivity so that way no large amount of rejections ever happens.

**Comment by sipah00** [comment]
:thinking:

**Comment by sipah00** [comment]
should I do it and check the performance?

**Comment by ChrisRackauckas** [comment]
I am not sure it's worth it because we should just fix the real issue.

https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/src/alg_utils.jl#L96

That should have a +1.

**Comment by ChrisRackauckas** [comment]
https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/src/perform_step/adams_bashforth_moulton_perform_step.jl#L1441

Did you check that both of these definitions give the same error estimate result?

**Comment by ChrisRackauckas** [comment]
>Reuse variable coefficients when curr_step_size/last_step_size ~ 1

I think the better option is to just set the default `qsteady_max` to be higher on this algorithm, like 1.5. What this will do is that if the stepsize change is less than a factor of 1.5, it'll keep it at exactly 1. Then what you can do is have a check and if the stepsizes haven't changed, reuse the coefficients.

**Comment by sipah00** [comment]
If the step size is constant then It will give same result.

**Comment by ChrisRackauckas** [comment]
Exactly, so you can reuse the coefficients you've already calculated and skip the computation.

**Comment by ChrisRackauckas** [comment]
https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/src/perform_step/adams_bashforth_moulton_perform_step.jl#L1417-L1420

This is your re-rejection issue. If you have a rejection, what happens is you are changing `dt` again, and now your vector of `dt`s is incorrect. Only do this when `integrator.EEst <= one(integrator.EEst)` (and make a comment that this may be incorrect after an event which will need to get handled later). This issue shows up in each of the Adams methods.

**Comment by sipah00** [comment]
intially I used a bool `success` for it, if last step is successful then do `dts` vector shifting but if step is not successful, it automatically reset values of vars?? and then I removed  this bool

**Comment by ChrisRackauckas** [comment]
This unshifting on rejection here:

https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/src/perform_step/adams_bashforth_moulton_perform_step.jl#L1434

is another way to do it, and that would be clean (and work well with events)

**Comment by sipah00** [comment]
means before returning `nothing` do unshifting, but any changes in variables will be discarded if the step is unsuccessful :thinking: so why it needs unshifting.

**Comment by ChrisRackauckas** [comment]
>but any changes in variables will be discarded if the step is unsuccessful

When is this done?

**Comment by sipah00** [comment]
I think once you told me, dont think about rejection do it assuming no rejection.

**Comment by ChrisRackauckas** [comment]
It discards the changes to the integrator (`u`, `t`, etc.), but it doesn't do anything to the cache (how would it know to reset this special `dts` vector that only exists for a few algorithms?)

**Comment by sipah00** [comment]
https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/src/alg_utils.jl#L96
why +1 here

**Comment by ChrisRackauckas** [comment]
Optimal dt is always calculated with order + 1. In Hairer this is k+2.

**Comment by ChrisRackauckas** [comment]
Nevermind, the +1 is already there.

**Comment by ChrisRackauckas** [comment]
Okay, it's looking much better now. Next step it should get profiled.

**Comment by sipah00** [comment]
Okay

**Comment by YingboMa** [comment]
closed by #389
