### ISSUE TITLE
Native Adams-Bashforth-Moulton methods

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/OrdinaryDiffEq.jl#4]
[A table of methods for different orders can be found here](http://www.mymathlib.com/diffeq/adams/). First the these fixed orders will be implemented and tested, and then a variable order implementation would be nice.

**Comment by sipah00** [comment]
@ChrisRackauckas, I want to work on this issue.

**Comment by ChrisRackauckas** [comment]
Cool. Fixed and variable time step? I think fixed time step should go first since it does have a lot of uses. A nice way to do higher order ones is to simply check if the number of iterations is too low, and if so, call the lower order `perform_step!` via an embedded `cache`. The IRKN3 method shows this (though it's quite complicated there and could probably be simplified a bit).

I am still contemplating which formulation to go with for variable time step (ddeabm's variable coefficient form vs cvode's Nordsieck form)

**Comment by ChrisRackauckas** [comment]
There was some code awhile back that was abandoned, this may be worth looking at:

https://github.com/JuliaDiffEq/ODE.jl/pull/106

**Comment by sipah00** [comment]
I will first implement fixed orders methods. As suggested in JuliaDiffEq/ODE.jl#106 should I put these fixed orders methods to a new file named (adams_methods.jl)?

**Comment by ChrisRackauckas** [comment]
No. The old ODE.jl way shouldn't be followed. The reasons are long, but the simple way to explain it is that there's not much code shared between the algorithms, making there no DRY way to do anything like event handling, interpolations, etc. 

The OrdinaryDiffEq.jl integrators are documented in the developer documentation:

http://devdocs.juliadiffeq.org/latest/

Making new algorithms is documented specifically:

http://devdocs.juliadiffeq.org/latest/contributing/adding_algorithms.html

If you need any help, just ask questions in the Gitter channel: https://gitter.im/JuliaDiffEq/Lobby .

**Comment by ChrisRackauckas** [comment]
The practical fixed timestep and fixed order methods are completed. We should look to do a variable order variable timestep method of variable-coefficient form, matching something like DEABM. A description can be found in Hairer I and some of the coefficient generators from JuliaDiffEq/ODE.jl#106 can be used. Instead of doing a Bashforth separately, we should just make this a PECE with a user choice of the number of corrections, so 0 corrections is Adams-Bashforth.

**Comment by sipah00** [comment]
@ChrisRackauckas, I am working on variable order variable timestep method.
I have a doubt: to change `curr_dt` to `next_dt` what should be the minimum difference between `curr_dt` and `next_dt` by default if the user does not provide it.

**Comment by ChrisRackauckas** [comment]
You don't need to handle that. Instead, just provide an error estimator on the end of the method if `integrator.adaptive`. See an adaptive method like `BS3` for how that's done.

**Comment by ChrisRackauckas** [comment]
The fixed order methods have been done. Now all that's needed is the variable order version.

**Comment by ChrisRackauckas** [comment]
This is done.
