### ISSUE TITLE
Newton method's stopping criterion

### ISSUE THREAD

**Issue by YingboMa** [JuliaDiffEq/OrdinaryDiffEq.jl#446]
I revisited Hairer's derivation about Newton method's stopping criterion. I found that his derivation assumes linear convergence. Thus, I derived the stopping criterion again with the assumption of quadratic convergence. https://www.overleaf.com/18019463scttnfmsszcw#/68253956/ We should change the stopping criterion [here](https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/src/nlsolve_utils.jl#L81-L82) and benchmark it.

**Comment by ChrisRackauckas** [comment]
The algorithm is linear since it's only quasi-Newton. Newton would take and factorize a Jacobian every step instead of once.
