### ISSUE TITLE
Improve Nonlinear Solver

### ISSUE THREAD

**Issue by YingboMa** [JuliaDiffEq/OrdinaryDiffEq.jl#468]
@ChrisRackauckas mentioned this in https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/pull/451.

> One thing to add to the nonlinear solvers is that, if the nonlinear part is actually an AbstractDiffEqOperator, then it's linear and the linsolve can be used instead. This is important in IMEX algorithms where you might have the stiff part be the linear PDE discretization, and thus instead of doing all of the extra steps you just do a linear solve and get "immediate convergence".

**Comment by ChrisRackauckas** [comment]
I think this is done?
