### ISSUE TITLE
Apply changes to ExponentialUtilities.jl to the ExpRK integrators

### ISSUE THREAD

**Issue by MSeeker1340** [JuliaDiffEq/OrdinaryDiffEq.jl#517]
https://github.com/JuliaDiffEq/ExponentialUtilities.jl/pull/1

Currently the only breaking change is the dropping of `cache` in `expv(!)` and `phiv(!)`.

**Comment by ChrisRackauckas** [comment]
How do you plan to do the breaking change?

**Comment by MSeeker1340** [comment]
For now https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/commit/fc257d5cb902b256ad926ad164b6097316911a58 will do. Since @jagot is still actively developing on his part I would expect more breaking changes in the future, at which point I'll implement those in OrdinaryDiffEq along the way. And after that we can merge the branch and push a release for both ExponentialUtilities and OrdinaryDiffEq.

**Comment by MSeeker1340** [comment]
Resolved as of https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/tree/v4.15.1.
