### ISSUE TITLE
Callback with zero time does not rollback integrator

### ISSUE THREAD

**Issue by pengwyn** [JuliaDiffEq/OrdinaryDiffEq.jl#538]
I've been debugging a very rare bug that I have had when using a callback set. I think I've traced it back to the `apply_callback!` function, as it seems as though the variable `cb_time` is not treated properly.

The lines in particular are here:
https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/c9910b510c30bdf657d47736ea3086b1f7efc729/src/callbacks.jl#L201-L204

Basically, if `cb_time == 0` then the function will not roll back the integrator to an earlier time. I have "fixed" it temporarily by removing the if test. However, I suspect that wasn't the intention and there was meant to be an `else` block with code to avoid the interpolation and step directly back to `tprev`, `uprev`, etc...

I would like to make a pull request, reusing a lot of `change_t_via_interpolation!` but avoiding the interpolation itself but I don't know if this is the correct way to do the step back.

**Comment by ChrisRackauckas** [comment]
If `cb_time==0`, then the time of the next event is the same as the current time. That seems like it should error?

Note that with https://github.com/JuliaDiffEq/DiffEqBase.jl/pull/164 we just unified all of DiffEq to use the same callback handling code, and with that we'll be digging in to fix a few problems with ContinuousCallback event detection.

**Comment by ChrisRackauckas** [comment]
Can we get an example of what's going on here? I wonder if it's related to https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues/353 . We're going to be working to make the ContinuousCallback more robust tomorrow but cannot help this without understanding why `cb_time==0` shouldn't just error (I think we'll add an error throw instead of ignoring) and what kind of setup could lead to this.

**Comment by pengwyn** [comment]
I'm been debugging my code and there is somewhat of a logic failure in the setup of my physical system. I think I was fixing a symptom rather than the problem before.

I now realise that `cb_time` being zero was actually something I should have treated as a bug. The cause in my code was because the `condition` function for the `ContinuousCallback` was not evaluating to the same values at the root finding stage as it was evaluating in the integration itself. I was using `get_du(int)` in the condition function, not realising that `t` and `int.t` are different values. And also not realising that the derivative is not interpolated - which is embarrassingly obvious now that I think about it.

So my original problem is now a non-problem. But should I leave this issue open to encourage a pull request to implement an error for `cb_time==0`?

**Comment by ChrisRackauckas** [comment]
>I now realise that cb_time being zero was actually something I should have treated as a bug. The cause in my code was because the condition function for the ContinuousCallback was not evaluating to the same values at the root finding stage as it was evaluating in the integration itself. I was using get_du(int) in the condition function, not realising that t and int.t are different values. And also not realising that the derivative is not interpolated - which is embarrassingly obvious now that I think about it.

Yeah, this is one of the hard things to explain that `u,t` is there because it's an interpolated value. Maybe that needs better docs? But `integrator(t,Val{1})` will give the derivative.

>So my original problem is now a non-problem. But should I leave this issue open to encourage a pull request to implement an error for cb_time==0?

I just fixed it: https://github.com/JuliaDiffEq/DiffEqBase.jl/commit/01b377a3765453985db61ebd5092bc7c847e45c6

**Comment by ChrisRackauckas** [comment]
We fixed up some event detection problems in the last day or so. It might be worth trying this out again.
