### ISSUE TITLE
Support for using dual numbers in `tstops`

### ISSUE THREAD

**Issue by MSeeker1340** [JuliaDiffEq/OrdinaryDiffEq.jl#556]
In some parameter estimation problems with AD we end up with a `tstops` of dual numbers (e.g. as a result of discrete events' time being parameter dependent). This currently results in an error in OrdinaryDiffEq:

```julia
using OrdinaryDiffEq
using ForwardDiff: Dual
prob = ODEProblem((u,p,t) -> u, 1.0, (0.0, 1.0))

tstops = [0.2, 0.5]
sol = solve(prob, Tsit5(), tstops=tstops) # OK

tstops = Dual.(tstops)
sol = solve(prob, Tsit5(), tstops=tstops)
# ERROR: LoadError: MethodError: no method matching Float64(::Dual{Nothing,Float64,0})
...
```

The error message points to `tstop_saveat_disc_handling`, but simply patching that does not solve the issue and we need to take a systematic approach to this.

**Comment by ChrisRackauckas** [comment]
What about changing time to dual numbers?

**Comment by MSeeker1340** [comment]
```julia
prob_dual = ODEProblem((u,p,t) -> u, 1.0, Dual.((0.0, 1.0)))
tstops = Dual.([0.2, 0.5])
sol = solve(prob_dual, Tsit5(), tstops=tstops)
```

This still produces a error of converting `Dual` to `Float64` but at a different location:

https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/src/perform_step/low_order_rk_perform_step.jl#L541

**Comment by YingboMa** [comment]
That is because `integrator.fsallast` is typed `Float64`. The line number is messed up by macros.
https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/src/perform_step/low_order_rk_perform_step.jl#L547
```
prob_dual = ODEProblem((u,p,t) -> u, Dual(1.0), Dual.((0.0, 1.0)))
tstops = Dual.([0.2, 0.5])
sol = solve(prob_dual, Tsit5(), tstops=tstops)
```
works fine.

**Comment by MSeeker1340** [comment]
OK. I think it makes sense that to use dual number `tstops` we should also use dual number for `tspan` (in fact just any `t` type in general).

We should delegate the responsibility of making sure `tspan` is the correct type to the clients instead of doing major overhauls to OrdinaryDiffEq's internals.
