### ISSUE TITLE
Problem using an `LArray` of `Measurement` in the solvers

### ISSUE THREAD

**Issue by MSeeker1340** [JuliaDiffEq/OrdinaryDiffEq.jl#561]
MWE:

```julia
using OrdinaryDiffEq, LabelledArrays, Measurements

# u0_ms = [1.0 ± 0.1, 2.0 ± 0.1] # this is ok
u0 = @LArray [1.0, 2.0] (:a, :b)
err = @LArray [0.1, 0.2] (:a, :b)
u0_ms = u0 .± err
prob = ODEProblem((du,u,p,t) -> du .= u, u0_ms, (0.0, 1.0))
integrator = init(prob, Tsit5()) # UndefRefError
```

The cause of the error is here: https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/src/solve.jl#L203. The arguments to `copyat_or_push!` are:

   ```julia
ks = Array{LArray{Measurement{Float64},1,(:a, :b)},1}[]
rate_prototype = Measurement{Float64}[#undef, #undef]
```

In the push operation, `rate_prototype` is implicitly converted to an `LArray`. However that requires getting the elements of `rate_prototype` which are uninitialized, hence the error.

There're two ways we can go with it:

1. Change the fact that `similar` on an array of `Measurement` returns uninitialized values:
```julia
julia> x = [1.0, 2.0] .± 0.1
2-element Array{Measurement{Float64},1}:
 1.0 ± 0.1
 2.0 ± 0.1

julia> similar(x)
2-element Array{Measurement{Float64},1}:
 #undef
 #undef
```

This is not technically wrong as `similar` states that it is intended to "Create an uninitialized mutable array", although in most cases we do get some random values (e.g. `ForwardDiff.Dual` does this and so it does not have a problem).

~~2. Make sure `rate_prototype` is an `LArray`.~~

~~I think `rate_prototype` being a plain array is probably a bug, but not really sure why so as `LArray` should have type stability after the recent update. Maybe all the unit unwrapping code somehow interferes with this?~~

**Comment by MSeeker1340** [comment]
Oops... again forgot that `show` for an `LVector` only prints its contents. `rate_prototype` is of the correct type:

```julia
typeof(rate_prototype) = LArray{Measurement{Float64},1,(:a, :b)}
rate_prototype = Measurement{Float64}[#undef, #undef]
typeof(ks) = Array{Array{LArray{Measurement{Float64},1,(:a, :b)},1},1}
ks = Array{LArray{Measurement{Float64},1,(:a, :b)},1}[]
```

**Comment by MSeeker1340** [comment]
About `Measurement`'s behavior on `similar`: seems this is the expected behavior for user defined types:

```julia
julia> struct S
           val
       end

julia> Vector{S}(undef, 2)
2-element Array{S,1}:
 #undef
 #undef

julia> similar([1,2], S)
2-element Array{S,1}:
 #undef
 #undef
```

The uninitialized elements cause problems in `copyat_or_push!` because internally we're doing a recursive copy.

What I'm not sure is why `ForwardDiff.Dual` *does* initialize its values in an array context (the julia docs on `undef` isn't really helpful either: https://github.com/JuliaLang/julia/blob/d789231e9985537686052db9b2314c0d51656308/base/docs/basedocs.jl#L1568). But nevertheless since `Measurement`'s behavior is the norm we should modify `init` to properly handle the case.

The simplest solution is to use `zeros` instead of `similar` to enforce initialization (is it safe to assume all `Number` types have `zero` defined?). We can also simply `push!` onto `ks` instead of using `copyat_or_push!` since `rate_prototype` is a temporary object anyways, but I'm afraid this would have some unintended consequences (e.g. does this break if `rate_prototype` is an `SVector`?)

**Comment by ChrisRackauckas** [comment]
I'm not sure we ever need to push rate_prototype anyways? We could just leave the first of the `ks` array empty for special interpolants? But I don't actually get why pushing isn't working. `similar` always has had this undef usage on non-Float64 types and it's never been an issue before.

>We can also simply push! onto ks instead of using copyat_or_push! since rate_prototype is a temporary object anyways, but I'm afraid this would have some unintended consequences (e.g. does this break if rate_prototype is an SVector?)

No but it breaks pre-allocation.

**Comment by MSeeker1340** [comment]
Also btw plain arrays of uninitialized `Measurement` is able to pass because for some reason `copy` and `deepcopy` such an array is allowed, but not so for `LArray` (which uses the default copy behavior of an `AbstractArray`). Again the `undef` handling is puzzling to me but the issue can be sidestepped if we don't use uninitialized arrays in the first place.

**Comment by ChrisRackauckas** [comment]
`zero`ing does have a cost though, but in most places we did change to `zero` for this reason. Actually, it's probably just the prototype arrays that are uninitialized these days?
