### ISSUE TITLE
cache_iter not defined

### ISSUE THREAD

**Issue by BrantCarlson** [JuliaDiffEq/OrdinaryDiffEq.jl#568]
cache_iter, called in addat! and deleteat! in integrator_interface.jl, is not defined and doesn't seem to be referenced anywhere else in the code.  Left over from a previous edit but not removed?

Thanks for all the hard work!

(I'm reverting to an earlier version for now and things seem fine, though my code evidently has other bugs...)

**Comment by ChrisRackauckas** [comment]
Fixed by https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/commit/307e5863a03c110db7dcd654333c3333bc1e4a86
