### ISSUE TITLE
SymplecticEuler implementation is wrong

### ISSUE THREAD

**Issue by mseri** [JuliaDiffEq/OrdinaryDiffEq.jl#577]
While working on some numerical comparisons, we noticed that the SymplecticEuler seems to be in fact a simple Euler method. You can easily see that it is not symplectic applying it to a damped harmonic oscillator. To give credit where credit is due, the first to spot the issue was @mvermeeren.

Also the Velocity Verlet seems to be initialised slightly off-energy, but that’s not a big issue.

**Comment by YingboMa** [comment]
Thanks a lot for reporting this issue. Could you please try your example in my fixed branch in #578?

**Comment by mseri** [comment]
Thanks. I will not have access to my laptop until the 2nd of January. I will test it and if it is not enough I will let you know in case there is any issue (though the fix looks correct tbh)
