### ISSUE TITLE
Add `@reexport using DiffEqBase`

### ISSUE THREAD

**Issue by Datseris** [JuliaDiffEq/OrdinaryDiffEq.jl#58]
It would be a good and non-invasive change that would allow one to simply `using OrdinaryDiffEq` to solve the problem. 

I could do a PR for it since it needs the addition of only 2 lines, however I would also had to change REQUIRE. Maybe it;s best for the owner to do that since tagging new versions is super strict on the REQUIRE files (as I've come to know).

**Comment by ChrisRackauckas** [comment]
I think this, if done, should be more DiffEq-wide. As in, if OrdinaryDiffEq does it, then StochasticDiffEq, Sundials, etc. should all do it to keep it uniform.

The question to answer is, what happens if two packages re-export the same package? I don't want this leading to issues in DifferentialEquations.jl. I would like to see a test where 1 base module is re-exported from 3 intermediate modules, which are all re-exported from a top level package. That's the test I want to run before making the change, which is why this lagged behind a bit. If that works fine (no warnings, no compilation problems, etc.), then I think it's probably a good idea.

**Comment by Datseris** [comment]
I think this will be a *big* improvement for "outsiders", people that want to have absolutely nothing to do with developement and/or internals of a package. As Julia becomes more and more famous more non-developer people will show up.

For them I already know from personal experience that all these complications are quite a hassle: which name is in `DiffEqBase`, which is in `OrdinaryDiffEq` , "oh I need to use `OrdinaryDiffEq` for this solver but I need to use `DiffEqBase` for the `solve function`" (by the way this doesn't make sense even for me).

I personally think your work is very praiseworthy and these suggestions will make it clear to people that really don't want to deal with all this hassle.

**Comment by ChrisRackauckas** [comment]
First we need to make sure reexport actually works correctly for this. If it does, then I am happy to make the change.

**Comment by Datseris** [comment]
I hope this code snipet can help. It works without any conflictions but it is very basic.
```
module Basic
export basic1,basic2

basic1(x,y) = x+y
struct basic2
  x
  y
end

end

module Intermediate1
export inter1, inter2
using Reexport
@reexport using Basic

inter1(x,y) = 2basic1(x,y)
struct inter2
  x
  y::basic2
end

end

module Intermediate2
export inter3, inter4
using Reexport
@reexport using Basic

inter3(x,y) = 4basic1(x,y)
struct inter4
  x
  y::basic2
end

end


module Frontend
export megacontainer, front1
using Reexport
@reexport using Basic
@reexport using Intermediate1, Intermediate2

front1(x,y) = inter1(x,y) + inter3(x,y)
struct megacontainer
  x::basic2
  y::inter4
end

end

using Frontend
front1(3,4)
megacontainer(basic2(1,2), inter4(3,basic2(4,5)))
```

**Comment by ChrisRackauckas** [comment]
💯 I'm convinced. I'll do this with the next release of the solvers.

**Comment by ChrisRackauckas** [comment]
All of the solvers are setup with this now. It'll be in the next release.

**Comment by Datseris** [comment]
Awesome!

**Comment by Datseris** [comment]
I am getting this in the package I am creating:
```
WARNING: both OrdinaryDiffEq and DiffEqBase export "DEOptions"; uses of it in module DynamicalSystems must be qualified
```
How do I qualify that? I am only using the names `solve` and `ODEProblem`, nothing else.

**Comment by ChrisRackauckas** [comment]
I believe I have fixed that. It was a naming issue.
