### ISSUE TITLE
Nomenclature of SSPRK methods

### ISSUE THREAD

**Issue by YingboMa** [JuliaDiffEq/OrdinaryDiffEq.jl#608]
The nomenclature of SSPRK methods used to be in the form of `SSP[stage][order][embedded order]`. However, it is inevitable to have name collisions with this naming scheme. Also, newly added methods have an inconsistent nomenclature.

Namely,
https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/pull/606 RKM
https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/pull/598 RK46NL
https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/pull/596 LDDRK64
https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/pull/600 ORK256
https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/pull/607 LDDRK46
https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/pull/599 LDDRK25

We should perhaps rename them.

CC: @keshavseksaria @saurabhkgp21 @arnav-t @deeepeshthakur

**Comment by ChrisRackauckas** [comment]
I don't think so. It's fine to use the name the authors give to the method here. It just so happens that the author of most of the SSPRK methods has tended to name them in the form `SSP[stage][order][embedded order]`, and a lot of authors followed suit, hence it seeming like an enforced naming scheme.

**Comment by ChrisRackauckas** [comment]
Though stage should come before order. `LDDRK46` should be `LDDRK64`, but there are two of those methods, so we should add the author's name to the improved one: `CFRLDDRK64`.

**Comment by deeepeshthakur** [comment]
@ChrisRackauckas @YingboMa  I'll make the respective changes to suit Chris's suggestion because the first one already has one conflict.

**Comment by ranocha** [comment]
I have to admit that I like longer but more detailed names, e.g. `CarpenterKennedy2N54` instead of `CK2N54`. But that might be just because I know the names of the authors developing the schemes I would like to use. Nevertheless, there are still some widely used schemes such as `SSPRK33` that do not need to include the name of the developers.
