### ISSUE TITLE
Investigate controllers' mysterious effect on performance

### ISSUE THREAD

**Issue by YingboMa** [JuliaDiffEq/OrdinaryDiffEq.jl#684]
![controller_bench](https://user-images.githubusercontent.com/17304743/53693134-df604700-3d69-11e9-9678-21aec8a1a29e.png)

```julia
using OrdinaryDiffEq, DiffEqDevTools, Plots, ParameterizedFunctions, Sundials
gr()
rober = @ode_def begin
  dy₁ = -k₁*y₁+k₃*y₂*y₃
  dy₂ =  k₁*y₁-k₂*y₂^2-k₃*y₂*y₃
  dy₃ =  k₂*y₂^2
end k₁ k₂ k₃
prob = ODEProblem(rober,[1.0;0.0;0.0],(0.0,1e11),(0.04,3e7,1e4))

# compute test solution
const TEST_SOL = TestSolution(solve(prob,CVODE_BDF(),abstol=1/10^14,reltol=1/10^14))

abstols = @. 1/10^(5:8)
reltols = @. 1/10^(1:4)

setups = [
          Dict(:alg=>Kvaerno5(controller=:Predictive)),
          Dict(:alg=>Kvaerno5(controller=:Standard)),
          Dict(:alg=>Kvaerno5(controller=:PI)),
          Dict(:alg=>KenCarp4(controller=:Predictive)),
          Dict(:alg=>KenCarp4(controller=:Standard)),
          Dict(:alg=>KenCarp4(controller=:PI)),
         ]
names = ["Kvaerno5 predictive" "Kvaerno5 standard" "Kvaerno5 PI" "KenCarp4 predictive" "KenCarp4 standard" "KenCarp4 PI"]
wp = WorkPrecisionSet(prob,abstols,reltols,setups;names=names,
                  save_everystep=false,appxsol=TEST_SOL,maxiters=Int(1e5))
plot(wp, legend=:bottomright, linewidth=1.5, markersize=2, dpi=200)
```

Somehow, `KenCarp4` performs the best with the PI controller, while `Kvaerno5` performs the best with the standard controller.

**Comment by ChrisRackauckas** [comment]
And predictive needs help. We should make predictive do the dual predictive+standard that Hairer uses in Radau.

**Comment by deeepeshthakur** [comment]
@YingboMa I'm not able to reproduce this result. This is what I'm getting.
![image](https://user-images.githubusercontent.com/26359940/54043803-7bb79d00-41f3-11e9-95f9-4d396508b2d5.png)
 
`integrator.opts.dtmax` is used to in both standard and predictive controllers to restrict stepsize, it's never changed. 
`integrator.opts.dtmax = integrator.sol.prob.tspan[2] - integrator.sol.prob.tspan[1]` 
and this is constant throughout, which I think ideally should be changed after every accepted step 
```
ttmp = integrator.t + integrator.dt
if integrator.accept_step
integrator.opts.dtmax = integrator.sol.prob.tspan[2] - ttmp
end
```

**Comment by ChrisRackauckas** [comment]
No, there is already time clamping, and handling it like that wouldn't be very floating point friendly. There shouldn't be a need to change dtmax.

**Comment by deeepeshthakur** [comment]
@ChrisRackauckas @YingboMa 
I did this. Using your setup just changing this line, I get.
```
wp = WorkPrecisionSet(prob,abstols,reltols,setups,qmax=2;names=names,
                  save_everystep=false,appxsol=TEST_SOL,maxiters=Int(1e5))
```
![image](https://user-images.githubusercontent.com/26359940/54082537-34d5be80-433d-11e9-8e37-a7fde7915360.png)

**Comment by deeepeshthakur** [comment]
The reason I chose `qmax=2` is that the controllers seem to unstable for `KenCarp Methods` for `qmax>2`

**Comment by ChrisRackauckas** [comment]
That's not a good test. You're testing CVODE with really low tolerances vs runs without a tolerance set (so high tolerance). `qmax` being that low basically amounts to forcing every simulation to be slow since dt won't grow fast, in order to hit lower tolerances than the user asks for. Notice how the errors aren't scaling in the graph that you show: that's a very very bad sign.

**Comment by deeepeshthakur** [comment]
So you are saying that the graph should basically be sort of a straight line with negative slope.

**Comment by ChrisRackauckas** [comment]
yes

**Comment by deeepeshthakur** [comment]
Also, This gives
```
abstols = @. 1/10^(5:13)
reltols = @. 1/10^(1:9)
wp = WorkPrecisionSet(prob,abstols,reltols,setups;names=names,
                  save_everystep=false,appxsol=TEST_SOL,maxiters=Int(1e5))
plot(wp, legend=:bottomleft, linewidth=1.5, markersize=2, dpi=200)
```
![image](https://user-images.githubusercontent.com/26359940/54082957-5c2f8a00-4343-11e9-9ef5-5d324a4e9b12.png)

**Comment by YingboMa** [comment]
The first spike is most likely due to bad timing. Could you update to the
latest DiffEqDevTools?

**Comment by deeepeshthakur** [comment]
The above graph is almost the same.

**Comment by deeepeshthakur** [comment]
@ChrisRackauckas This is the plot after updating DiffeqDevTools
```
abstols = @. 1/10^(5:8)
reltols = @. 1/10^(1:4)
wp = WorkPrecisionSet(prob,abstols,reltols,setups,qmax=2;names=names,
                  save_everystep=false,appxsol=TEST_SOL,maxiters=Int(1e5))
plot(wp, legend=:topright, linewidth=1.5, markersize=2, dpi=200)
```
![image](https://user-images.githubusercontent.com/26359940/54083260-576cd500-4347-11e9-8b41-16065a5d5a28.png)

**Comment by deeepeshthakur** [comment]
@ChrisRackauckas This plot is exactly the same as the first plot where you suggested that the first spike is a very bad sign but this is what  I get after I updated DIffEqDevTools.
