### ISSUE TITLE
"Automatic dt setting has the wrong sign. Exiting. Please report this error."

### ISSUE THREAD

**Issue by mauro3** [JuliaDiffEq/OrdinaryDiffEq.jl#78]
When the objective function returns a NaN at tspan[1], this unhelpful error message is printed.  Probably should check for NaN and Inf in https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/src/initdt.jl .

**Comment by ChrisRackauckas** [comment]
Implemented. It'll be in the next release.
