### ISSUE TITLE
KenCarp4 on solving semi-discrete diffusion equation

### ISSUE THREAD

**Issue by isaacsas** [JuliaDiffEq/OrdinaryDiffEq.jl#839]
With default settings I'm getting pretty big differences in solving the semi-discrete diffusion equation with KenCarp4 vs Rodas5 through DEBio (generating the equation as a linear reaction model). This seems to be a newer issue, as the tutorial I'm taking this from, which was last generated 25 days ago, seems fine. Here is the example I'm looking at:

```julia
using DifferentialEquations, DiffEqBiological, Plots
N = 64
h = 1 / N
rn = @empty_reaction_network

for i = 1:N
    addspecies!(rn, Symbol(:u, i))
end
addparam!(rn, :β)
for i = 1:N
    (i < N) && addreaction!(rn, :β, (Symbol(:u,i)=>1,), (Symbol(:u,i+1)=>1,))
    (i > 1) && addreaction!(rn, :β, (Symbol(:u,i)=>1,), (Symbol(:u,i-1)=>1,))
end
addodes!(rn)
u₀ = zeros(N)
u₀[div(N,2)] = 10000
p = [1/(h*h)]
tspan = (0.,.01)
oprob = ODEProblem(rn, u₀, tspan, p)
sol = solve(oprob, KenCarp4())
times = [0., .0001, .001, .01]
plt = plot()
for time in times
    plot!(plt, 1:N, sol(time), fmt=fmt, xlabel="i", ylabel="uᵢ", label=string("t = ", time), lw=3)
end
plot(plt, ylims=(0.,10000.))
```

With `KenCarp4` I get:
![kencarp4](https://user-images.githubusercontent.com/9385167/61657809-dbd64980-ac91-11e9-836d-86c9b694fd73.png)

With `Rodas5` I get:
![rodas5](https://user-images.githubusercontent.com/9385167/61657823-e264c100-ac91-11e9-8597-160a94f407a2.png)
which looks more like I'd expect.

**Comment by isaacsas** [comment]
To add, it's the green solution at time `.001` that looks strange in `KenCarp4`.

**Comment by ChrisRackauckas** [comment]
This looks like it's just a tolerance thing.

```julia
using OrdinaryDiffEq, DiffEqBiological, Plots
N = 64
h = 1 / N
rn = @empty_reaction_network

for i = 1:N
    addspecies!(rn, Symbol(:u, i))
end
addparam!(rn, :β)
for i = 1:N
    (i < N) && addreaction!(rn, :β, (Symbol(:u,i)=>1,), (Symbol(:u,i+1)=>1,))
    (i > 1) && addreaction!(rn, :β, (Symbol(:u,i)=>1,), (Symbol(:u,i-1)=>1,))
end
addodes!(rn)
u₀ = zeros(N)
u₀[div(N,2)] = 10000
p = [1/(h*h)]
tspan = (0.,.01)
oprob = ODEProblem(rn, u₀, tspan, p)
sol = solve(oprob, KenCarp4(), reltol=1e-6)
times = [0., .0001, .001, .01]
plt = plot()
for time in times
    plot!(plt, 1:N, sol(time), xlabel="i", ylabel="uᵢ", label=string("t = ", time), lw=3)
end
plot(plt, ylims=(0.,10000.))
```

gives the same plot as Rodas5. The nonlinear solver must be exiting early thinking it's okay. This doesn't give cause for alarm since it's not necessarily incorrect low accuracy behavior, just different low accuracy behavior. If there's an example with a big difference, I'd like to get my hands on it.

**Comment by isaacsas** [comment]
Interesting. I guess something changed with the nonlinear solver between the first time I ran the simulation and made the notebook, and when it was updated and developed the weird kink at the default tolerance. Good to know that it is just a tolerance issue though.
