### ISSUE TITLE
AutoTsit5 example from documentation doesn't work

### ISSUE THREAD

**Issue by dburov190** [JuliaDiffEq/OrdinaryDiffEq.jl#855]
This line from the documentation
`tsidas_alg = AutoTsit5(Rodas5(), nonstifftol = 11/10)`
produces an error
`ERROR: LoadError: MethodError: no method matching #AutoSwitch#357(...)`

I'm on Julia 1.1 and using `OrdinaryDiffEq.jl` version 5.13.0.

Also, could you please elaborate on what exactly `nonstifftol` and `stifftol` do, besides that they are just "used to determine whether it's stiff or not"? At least, what effect each of them has when increased/decreased. I couldn't find any explanation in the documentation except for:

> nonstifftol and stifftol are the tolerances associated with the stiffness comparison against the stability region

**Comment by ChrisRackauckas** [comment]
This actually looks like a bug. @YingboMa can you fix this up and update the docs today? It seems a little tricky: I am not sure why the constructor is changing one of them to Float64 🤷‍♂
