### ISSUE TITLE
deleteat! fails due to undefined variable

### ISSUE THREAD

**Issue by BrantCarlson** [JuliaDiffEq/OrdinaryDiffEq.jl#87]
Calling `deleteat!(integrator,idx)` in a callback fails because the source code for `deleteat!` (line 114 in integrator_interface.jl) attempts to access a local variable `cache` that is undefined.

I think this just needs to be `integrator.cache` as other functions in the same file that providing versions of similar functions without the explicit `cache` argument simply provide `integrator.cache` in its place.  Swapping for `integrator.cache` seems to fix the problem in question, though I have not tested the results and am not entirely sure I understand the cache system.  There also appears to be a similar issue with `addat!` though I haven't used that one personally.

**Comment by ChrisRackauckas** [comment]
Yes, I don't know how that went missing but it needs to be `integrator.cache`. Would you like to submit a PR to receive the credit?

**Comment by BrantCarlson** [comment]
Nah, just go ahead and fix it whenever you get the chance.

Thanks for all your hard work!

**Comment by ChrisRackauckas** [comment]
Will be in the next release.
