### ISSUE TITLE
Units issue in `add_tstop!` and `add_saveat!`

### ISSUE THREAD

**Issue by goretkin** [JuliaDiffEq/OrdinaryDiffEq.jl#908]
https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/a0c90a790ec22e62f39244827d14dea681322736/src/integrators/integrator_interface.jl#L85

```julia
  integrator.tdir * (t - integrator.t) < 0 && error("Tried to add a saveat that is behind the current time. This is strictly forbidden")
  push!(integrator.opts.saveat, integrator.tdir * t)
```
Probably `integrator.tdir` should stay dimensionless, and `0` just needs to have the right units.

There's another occurrence just below it, too.

**Comment by devmotion** [comment]
Thanks! We should just replace `0` with `zero(integrator.t)`. `tdir` shouldn't be an issue, it's defined as unitless quantity since `sign` strips units (e.g., `sign(1.0u"s") == 1.0`).
