### ISSUE TITLE
Cell growth example, resize not working with automatic switching solver

### ISSUE THREAD

**Issue by ghyatzo** [JuliaDiffEq/OrdinaryDiffEq.jl#958]
Following up on #702 
I have run some tests and i think i found the culprit.
I could reproduce on julia 1.2.0 and DiffEq 6.8.0

The wiki example was solved with `sol = solve(prob,callback=callback)`.
While the examples deemed as working in #702 (which indeed they are) solve with 
`sol = solve(prob,Tsit5(),callback=callback)` instead.

I've tested on my system and both examples in #702, if `Tsit5()` is not passed, the resize function fails and consequently the whole script.

P.S. I tried many different combinations and the only time it failed to run was without `Tsit5()`

**Comment by ChrisRackauckas** [comment]
Thanks for the example. Isolating it really helps, and found a missing method for composite iteration. The fix is in https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/pull/959 .

**Comment by ChrisRackauckas** [comment]
Fixed by https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/pull/959
