### ISSUE TITLE
Tests freezing or timing out on PkgEval since July 19th

### ISSUE THREAD

**Issue by tkelman** [JuliaDiffEq/OrdinaryDiffEq.jl#96]
A heads up that I noticed looking through which packages were taking especially long on pkgeval - see https://github.com/JuliaCI/pkg.julialang.org/commits/gh-pages/logs/OrdinaryDiffEq_0.6.log, that's supposed to update daily, but this package hasn't finished since July 19th. That might correspond to the day 2.11.1 was tagged? Or maybe a dependency changed version that day and caused this.

**Comment by ChrisRackauckas** [comment]
I did have some tests get longer at around that time. Would that do it?

**Comment by tkelman** [comment]
That or overly verbose logging maybe. Are your tests parallelized at all?

**Comment by ChrisRackauckas** [comment]
No, the tests are parallel, but there's a lot of printing.

**Comment by tkelman** [comment]
Can you reduce that? Make verbose mode non default?

**Comment by ChrisRackauckas** [comment]
The tests only printout the test sets. They've gotten longer, but not much more verbose in a long time.

**Comment by ChrisRackauckas** [comment]
I pruned the tests a bunch to pull the timings down. Will this effect not be checked until this is tagged?

**Comment by tkelman** [comment]
Correct

**Comment by ChrisRackauckas** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/10649 should fix it.

**Comment by tkelman** [comment]
Cool, thanks. Will get to merging that shortly.
