### ISSUE TITLE
Error with Tracked Array and ROCK2() with diffeq_adjoint

### ISSUE THREAD

**Issue by collinwarner** [JuliaDiffEq/OrdinaryDiffEq.jl#980]
I am trying to use the ROCK2 to solve a neural PDE and running into an error with the tracked array I am using. There is no problem if I use Tsit5 as my method and was hoping for a solution to this discrepancy. I have simplified my code down to a MWE below:

```Julia
using OrdinaryDiffEq, Flux, DiffEqFlux
#sample random data to set up ODEproblem
tspan = (0.0f0,1.5f0)
x = param(randn(2))
inputs = 1

#Error with using tracked u with ROCK2 odesolver
function dudt(u::TrackedArray,pp,t)
    Flux.Tracker.collect(u)
end
#error occurs when ROCK2() is used works for Tsit5()
#run above
current_model = ODEProblem(dudt, x, tspan, inputs)
diffeq_adjoint(inputs, current_model, ROCK2(); u0 = x)
```

Then when running I receive the error message at the bottom. Any help would be appreciated. Thanks!

LoadError: MethodError: no method matching round(::Tracker.TrackedReal{Float64}, ::RoundingMode{:Down})
Closest candidates are:
  round(::Real, ::RoundingMode; digits, sigdigits, base) at floatfuncs.jl:129
  round(!Matched::Float64, ::RoundingMode{:Down}) at float.jl:366
  round(!Matched::Float32, ::RoundingMode{:Down}) at float.jl:367
  ...
in expression starting at C:\Users\Collin\Documents\MIT\UROP\Rackauckas\MWE.jl:14
#round#541 at floatfuncs.jl:134 [inlined]
round at floatfuncs.jl:129 [inlined]
#floor#543 at floatfuncs.jl:152 [inlined]
floor at floatfuncs.jl:152 [inlined]
perform_step!(::OrdinaryDiffEq.ODEIntegrator{ROCK2,false,TrackedArray{…,Array{Float64,1}},Float32,Int64,Tracker.TrackedReal{Float64},Float32,Float32,Array{TrackedArray{…,Array{Float64,1}},1},ODESolution{Tracker.TrackedReal{Float64},2,Array{TrackedArray{…,Array{Float64,1}},1},Nothing,Nothing,Array{Float32,1},Array{Array{TrackedArray{…,Array{Float64,1}},1},1},ODEProblem{TrackedArray{…,Array{Float64,1}},Tuple{Float32,Float32},false,Int64,ODEFunction{false,typeof(dudt),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{,Tuple{}}},DiffEqBase.StandardODEProblem},ROCK2,OrdinaryDiffEq.InterpolationData{ODEFunction{false,typeof(dudt),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Array{TrackedArray{…,Array{Float64,1}},1},Array{Float32,1},Array{Array{TrackedArray{…,Array{Float64,1}},1},1},OrdinaryDiffEq.ROCK2ConstantCache{Tracker.TrackedReal{Float64},Tracker.TrackedReal{Float64},TrackedArray{…,Array{Float64,1}}}},DiffEqBase.DEStats},ODEFunction{false,typeof(dudt),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},OrdinaryDiffEq.ROCK2ConstantCache{Tracker.TrackedReal{Float64},Tracker.TrackedReal{Float64},TrackedArray{…,Array{Float64,1}}},OrdinaryDiffEq.DEOptions{Tracker.TrackedReal{Float64},Tracker.TrackedReal{Float64},Float32,Float32,typeof(DiffEqBase.ODE_DEFAULT_NORM),typeof(LinearAlgebra.opnorm),CallbackSet{Tuple{},Tuple{}},typeof(DiffEqBase.ODE_DEFAULT_ISOUTOFDOMAIN),typeof(DiffEqBase.ODE_DEFAULT_PROG_MESSAGE),typeof(DiffEqBase.ODE_DEFAULT_UNSTABLE_CHECK),DataStructures.BinaryHeap{Float32,DataStructures.LessThan},DataStructures.BinaryHeap{Float32,DataStructures.LessThan},Nothing,Nothing,Int64,Array{Float32,1},Array{Float32,1},Array{Float32,1}},TrackedArray{…,Array{Float64,1}},Tracker.TrackedReal{Float64},Nothing}, ::OrdinaryDiffEq.ROCK2ConstantCache{Tracker.TrackedReal{Float64},Tracker.TrackedReal{Float64},TrackedArray{…,Array{Float64,1}}}, ::Bool) at rkc_perform_step.jl:19
perform_step!(::OrdinaryDiffEq.ODEIntegrator{ROCK2,false,TrackedArray{…,Array{Float64,1}},Float32,Int64,Tracker.TrackedReal{Float64},Float32,Float32,Array{TrackedArray{…,Array{Float64,1}},1},ODESolution{Tracker.TrackedReal{Float64},2,Array{TrackedArray{…,Array{Float64,1}},1},Nothing,Nothing,Array{Float32,1},Array{Array{TrackedArray{…,Array{Float64,1}},1},1},ODEProblem{TrackedArray{…,Array{Float64,1}},Tuple{Float32,Float32},false,Int64,ODEFunction{false,typeof(dudt),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{,Tuple{}}},DiffEqBase.StandardODEProblem},ROCK2,OrdinaryDiffEq.InterpolationData{ODEFunction{false,typeof(dudt),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Array{TrackedArray{…,Array{Float64,1}},1},Array{Float32,1},Array{Array{TrackedArray{…,Array{Float64,1}},1},1},OrdinaryDiffEq.ROCK2ConstantCache{Tracker.TrackedReal{Float64},Tracker.TrackedReal{Float64},TrackedArray{…,Array{Float64,1}}}},DiffEqBase.DEStats},ODEFunction{false,typeof(dudt),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},OrdinaryDiffEq.ROCK2ConstantCache{Tracker.TrackedReal{Float64},Tracker.TrackedReal{Float64},TrackedArray{…,Array{Float64,1}}},OrdinaryDiffEq.DEOptions{Tracker.TrackedReal{Float64},Tracker.TrackedReal{Float64},Float32,Float32,typeof(DiffEqBase.ODE_DEFAULT_NORM),typeof(LinearAlgebra.opnorm),CallbackSet{Tuple{},Tuple{}},typeof(DiffEqBase.ODE_DEFAULT_ISOUTOFDOMAIN),typeof(DiffEqBase.ODE_DEFAULT_PROG_MESSAGE),typeof(DiffEqBase.ODE_DEFAULT_UNSTABLE_CHECK),DataStructures.BinaryHeap{Float32,DataStructures.LessThan},DataStructures.BinaryHeap{Float32,DataStructures.LessThan},Nothing,Nothing,Int64,Array{Float32,1},Array{Float32,1},Array{Float32,1}},TrackedArray{…,Array{Float64,1}},Tracker.TrackedReal{Float64},Nothing}, ::OrdinaryDiffEq.ROCK2ConstantCache{Tracker.TrackedReal{Float64},Tracker.TrackedReal{Float64},TrackedArray{…,Array{Float64,1}}}) at rkc_perform_step.jl:15
solve!(::OrdinaryDiffEq.ODEIntegrator{ROCK2,false,TrackedArray{…,Array{Float64,1}},Float32,Int64,Tracker.TrackedReal{Float64},Float32,Float32,Array{TrackedArray{…,Array{Float64,1}},1},ODESolution{Tracker.TrackedReal{Float64},2,Array{TrackedArray{…,Array{Float64,1}},1},Nothing,Nothing,Array{Float32,1},Array{Array{TrackedArray{…,Array{Float64,1}},1},1},ODEProblem{TrackedArray{…,Array{Float64,1}},Tuple{Float32,Float32},false,Int64,ODEFunction{false,typeof(dudt),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{,Tuple{}}},DiffEqBase.StandardODEProblem},ROCK2,OrdinaryDiffEq.InterpolationData{ODEFunction{false,typeof(dudt),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Array{TrackedArray{…,Array{Float64,1}},1},Array{Float32,1},Array{Array{TrackedArray{…,Array{Float64,1}},1},1},OrdinaryDiffEq.ROCK2ConstantCache{Tracker.TrackedReal{Float64},Tracker.TrackedReal{Float64},TrackedArray{…,Array{Float64,1}}}},DiffEqBase.DEStats},ODEFunction{false,typeof(dudt),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},OrdinaryDiffEq.ROCK2ConstantCache{Tracker.TrackedReal{Float64},Tracker.TrackedReal{Float64},TrackedArray{…,Array{Float64,1}}},OrdinaryDiffEq.DEOptions{Tracker.TrackedReal{Float64},Tracker.TrackedReal{Float64},Float32,Float32,typeof(DiffEqBase.ODE_DEFAULT_NORM),typeof(LinearAlgebra.opnorm),CallbackSet{Tuple{},Tuple{}},typeof(DiffEqBase.ODE_DEFAULT_ISOUTOFDOMAIN),typeof(DiffEqBase.ODE_DEFAULT_PROG_MESSAGE),typeof(DiffEqBase.ODE_DEFAULT_UNSTABLE_CHECK),DataStructures.BinaryHeap{Float32,DataStructures.LessThan},DataStructures.BinaryHeap{Float32,DataStructures.LessThan},Nothing,Nothing,Int64,Array{Float32,1},Array{Float32,1},Array{Float32,1}},TrackedArray{…,Array{Float64,1}},Tracker.TrackedReal{Float64},Nothing}) at solve.jl:372
#__solve#328 at solve.jl:5 [inlined]
__solve at solve.jl:4 [inlined]
#solve_call#442(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{,Tuple{}}}, ::typeof(DiffEqBase.solve_call), ::ODEProblem{TrackedArray{…,Array{Float64,1}},Tuple{Float32,Float32},false,Int64,ODEFunction{false,typeof(dudt),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{,Tuple{}}},DiffEqBase.StandardODEProblem}, ::ROCK2) at solve.jl:40
solve_call at solve.jl:37 [inlined]
#solve#443 at solve.jl:57 [inlined]
solve at solve.jl:45 [inlined]
#diffeq_adjoint#21 at layers.jl:54 [inlined]
(::getfield(DiffEqFlux, Symbol("#kw##diffeq_adjoint")))(::NamedTuple{(:u0,),Tuple{TrackedArray{…,Array{Float64,1}}}}, ::typeof(diffeq_adjoint), ::Int64, ::ODEProblem{TrackedArray{…,Array{Float64,1}},Tuple{Float32,Float32},false,Int64,ODEFunction{false,typeof(dudt),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{,Tuple{}}},DiffEqBase.StandardODEProblem}, ::ROCK2) at none:0
top-level scope at MWE.jl:14

**Comment by ChrisRackauckas** [comment]
@YingboMa could you look into whether this is similar to the StochasticDiffEq one?

**Comment by YingboMa** [comment]
No, it looks like that this is a different error.

**Comment by ChrisRackauckas** [comment]
Did https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/pull/984 fix this?

**Comment by ChrisRackauckas** [comment]
I guess not. Hmm, how is this avoided in StochasticDiffEq? It seems the eigen_est shouldn't be tracked?
