### ISSUE TITLE
Stiffness Detection

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/OrdinaryDiffEq.jl#99]
Should add stiffness detection estimates to as many RK methods as we can.

**Comment by ChrisRackauckas** [comment]
This describes how to switch back from a stiff method: https://ntrs.nasa.gov/archive/nasa/casi.ntrs.nasa.gov/20160005923.pdf

**Comment by ChrisRackauckas** [comment]
This isn't too difficult. Will add details on how its done later.

**Comment by ChrisRackauckas** [comment]
https://dl.acm.org/citation.cfm?id=355719.355722
https://pdfs.semanticscholar.org/9a1a/0b720e582afa96376c350fa824517e09c2eb.pdf
https://pdfs.semanticscholar.org/2264/dc971c816feb5e9c7ac0c85b44937c1e42fa.pdf
https://www.sciencedirect.com/science/article/pii/0898122177901122

**Comment by ashaywalke** [comment]
Hey @ChrisRackauckas,

While implementing the theory from Hairer II, it says h*lambda is near del S. Wanted to ask you if there is any function to check if the value of any variable lies NEAR any value.

**Comment by ChrisRackauckas** [comment]
Just do the comparison against del S = 3.3 via the ratio as he suggests in the next paragraph.

**Comment by ashaywalke** [comment]
@ChrisRackauckas 
To check stiffness I have defined a function. Wanted to ask you what should I consider 'v' here?
https://imgur.com/a/rJR87
```
function stiffnesschecker!(integrator, cache::DP5ConstantCache)
  d1 = -0.08536
  d2 = 0.08
  d3 = -0.0096
  d4 = 0.0052
  d5 = 0.00576
  d6 = -0.004
  k1 = f(uprev+c1*dt,g1)
  k2 = f(uprev+c2*dt,g2)
  k3 = f(uprev+c3*dt,g3)
  k4 = f(uprev+c4*dt,g4)
  k5 = f(uprev+c5*dt,g5)
  k6 = f(uprev+c6*dt,g6)
  k7 = f(uprev+c7*dt,g7)
  err1bar = dt*(d1*k1+d2*k2+d3*k3+d4*k4+d5*k5+d6*k6+d7*k7)
  val = abs(err1bar)/abs(EEst)

**Comment by ChrisRackauckas** [comment]
See 2.26, but you don't need to do any of those calculations above in the stiffness checkers since they are all already done.

**Comment by ChrisRackauckas** [comment]
Note that there is a PR which is almost completed which will do DP5 stiffness detection and alters the integrator to hold the requisite information. I think the next step is to add a max norm estimate on `Rodas5` and get a very basic `CompositeAlgorithm` implementation with a simple switching strategy to see how this all works out. Thanks @YingboMa for the plot: it really shows how it's doing.

**Comment by ChrisRackauckas** [comment]
https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/pull/275 was merged with the stiffness detection on DP5.
